### ISSUE TITLE
Kinetic Energy Buffers "glitching"

### ISSUE THREAD

**Issue by TheGuyRunningSouth** [BCA-Team/Buildcraft-Additions#147]
For whatever reason, since I updated to BCA 1.8.3, my small kinetic energy buffers will occasionally stop transmitting or receiving energy. Although their texture shows energy stored, the GUI shows zero energy stored, and all faces have reset to input. 

Once they do this, it is impossible to reset any face to output or disabled (shows in GUI, resets immediately when closed), and the kinetic energy buffer block is impossible to remove except by destruction through creative mode.

Currently using Buildcraft 6.2.6 and BCA 1.8.3. As you can tell from my screenshots, I do have other mods installed, but the setup pictured was working before with Buildcraft 6.1.8 and BCA 1.8. Since I have only updated Buildcraft, Buildcraft Additions, and TeamCoFH core (which I needed to make Buildcraft power function properly for some reason), I find other mod interaction unlikely. I can test in a purely Buildcraft + BCA + Eureka + CoFH core environment if you wish, though it is hard to reproduce this bug as it will work fine for days at a time.

I do thoroughly enjoy the mod, and am mostly letting you know in case other people have a similar issue. Sorry for the wall of text, I wanted to be informative and thorough.

Attached find screenshots showing the situation I have described.

Sincerely,

TheGuyRunningSouth
![keb_gui](https://cloud.githubusercontent.com/assets/10284522/5544049/6710ad32-8ac4-11e4-829c-be10f6a218a3.png)
![keb_gauge](https://cloud.githubusercontent.com/assets/10284522/5544055/7d95d690-8ac4-11e4-8a6b-c79c549a06a9.png)

**Comment by RagaRBM** [comment]
Sorry to interrupt an already closed issue.
@TheGuyRunningSouth That's strange. BuildCraft power works fine on me without TeamCOFHCore whatsoever.

**Comment by AEnterprise** [comment]
@RagaRBM while in general it's bad practice to comment on a closed issue but in cases like this (where it was closed due not being able to replicate the bug) i don't mind people doing it, i hope it leads to the tracking down of the bug so i can fix it
