### ISSUE TITLE
finish refinery and cooling tower

### ISSUE THREAD

**Issue by AEnterprise** [BCA-Team/Buildcraft-Additions#166]
refinery and cooling tower to replace the BC refinery

feature list:
- [x] multiblock patern for refinery
- [x] multiblock patern for cooling tower
- [x] modifying the registered recepies in the BC api to output a gas
- [x] make cooling tower convert that gas to the normal output
- [x] make refinery use heat and dynamic powerusage based on current heat
- [x] make cooling tower produce heat when cooling the gas to a fluid
- [x] make cooling tower use water to cool down
- [ ] make heating speed, cooling speed and base temp dependant on biome (needs some biome mod reserch
- [x] make refinery and cooling tower only accect valid inputs

**Comment by AEnterprise** [comment]
looks like rotation detection is also broken for the cooling tower, it doesn't form if the valve for the coolant is on a specific side

**Comment by BigXplosion** [comment]
are we still going to look into biomes for the heat or was this not possible?

**Comment by AEnterprise** [comment]
not sure, i think this might be something to be added later then

**Comment by BigXplosion** [comment]
can this be closed now?

**Comment by AEnterprise** [comment]
yeah it can
