### ISSUE TITLE
[Bug] [Minor] Machine Configurator's texture is mirrored in your hand.

### ISSUE THREAD

**Issue by iTitus** [BCA-Team/Buildcraft-Additions#257]

**Comment by AEnterprise** [comment]
yeah it is but that's due to how MC handles drawing it in 3D, nothing i can do about that, the same thing heapens with a wrench, sword, pickaxe, ... you just don't notice it cause of the colors

**Comment by iTitus** [comment]
Well I wanted to suggest mirroring the texture file...

**Comment by AEnterprise** [comment]
then it would still look mirrorered if you look at the one in your inventory

**Comment by iTitus** [comment]
When you mirror at the right axis (from bottom left to the top right) only the colors change.

**Comment by AEnterprise** [comment]
the problem with that is that if blue is the left side in your inventory it'll be right on your hand due to the 3d drawing, same if red would be left

**Comment by iTitus** [comment]
The order of the colors doesnt matter. The spiky thingie is just pointing backwards.

**Comment by AEnterprise** [comment]
oh wrong like that, i thought you ment the colors

**Comment by iTitus** [comment]
Will mirror later in the evening.

**Comment by iTitus** [comment]
Its just minor :P

**Comment by AEnterprise** [comment]
if you want it in 2.0 i need it in a few hours
