### ISSUE TITLE
stripe pipes breaking keb's should store the energy

### ISSUE THREAD

**Issue by AEnterprise** [BCA-Team/Buildcraft-Additions#259]
it would allow players to automate the charging and transportation of energy over larger distances, using a railroad or robots

requested by chilm, would be interesting to see what he can make with it

**Comment by iTitus** [comment]
Once #251 is merged, I can edit the EventListener again. Then I could do this.

**Comment by AEnterprise** [comment]
@iTitus don't do this using the eventhandler! this should be done by using the BC stripe pipe api, registering a handler to break the keb

**Comment by iTitus** [comment]
I thought of removing the lines with the wrench drop code. The KEB should always drop itself with power.

**Comment by AEnterprise** [comment]
i don't think so, i think it's better to do it this way, makes more sense to me as you are picking it up, witht the wrench, not breaking it

**Comment by iTitus** [comment]
Then you're right...
