### ISSUE TITLE
ID name mappings broken in existing world with BCA 2.0

### ISSUE THREAD

**Issue by jermangarc** [BCA-Team/Buildcraft-Additions#262]
Hello, installed BCA 2.0 today and it corrupted my test world, which is a copy of a server world. Had to revert back to BCA 1.8.4

http://pastebin.com/26qNiwY0

**Comment by BigXplosion** [comment]
did this crash your world? if not what happened to the items in world?

**Comment by jermangarc** [comment]
Yes it did crash. 

---- Minecraft Crash Report ----
// You're mean.

Time: 2/11/15 8:53 AM
Description: Ticking block entity

java.lang.ClassCastException: ic2.core.block.machine.tileentity.TileEntityMatter cannot be cast to jds.bibliocraft.tileentities.TileEntityWeaponCase
	at jds.bibliocraft.blocks.BlockWeaponCase.func_149709_b(BlockWeaponCase.java:463)
	at net.minecraft.world.World.func_72878_l(World.java:3424)
	at net.minecraft.world.World.func_72864_z(World.java:3429)
	at ic2.core.block.machine.tileentity.TileEntityMatter.isRedstonePowered(TileEntityMatter.java:373)
	at ic2.core.block.machine.tileentity.TileEntityMatter.func_145845_h(TileEntityMatter.java:145)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at jds.bibliocraft.blocks.BlockWeaponCase.func_149709_b(BlockWeaponCase.java:463)
	at net.minecraft.world.World.func_72878_l(World.java:3424)
	at net.minecraft.world.World.func_72864_z(World.java:3429)
	at ic2.core.block.machine.tileentity.TileEntityMatter.isRedstonePowered(TileEntityMatter.java:373)
	at ic2.core.block.machine.tileentity.TileEntityMatter.func_145845_h(TileEntityMatter.java:145)

-- Block entity being ticked --
Details:
	Name: Mass Fabricator // ic2.core.block.machine.tileentity.TileEntityMatter
	Block type: ID #1140 (tile.BiblioCase // jds.bibliocraft.blocks.BlockWeaponCase)
	Block data value: 14 / 0xE / 0b1110
	Block location: World: (333,64,-1762), Chunk: (at 13,4,14 in 20,-111; contains blocks 320,0,-1776 to 335,255,-1761), Region: (0,-4; contains chunks 0,-128 to 31,-97, blocks 0,0,-2048 to 511,255,-1537)
	Actual block type: ID #1140 (tile.BiblioCase // jds.bibliocraft.blocks.BlockWeaponCase)
	Actual block data value: 14 / 0xE / 0b1110
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

**Comment by BigXplosion** [comment]
yup this seems like your mappings have all been shifted, but I thought we prevented that :/

**Comment by jermangarc** [comment]
Sorry for the bad news! Yeah this map is on server that's been on for two years now. I'll just wait for the fix? maybe if I'm lucky, lol.

**Comment by AEnterprise** [comment]
ok this is odd, some things should indeed have been remaped (the old dusts to a converter item) looks like something went wrong but i have no idea how that could have heapened

**Comment by jermangarc** [comment]
Here is the startup log if it helps. I know, that's one big modpack. It's been a year in the making.
https://dl.dropboxusercontent.com/u/72156241/BCA-crash-startup-log.log

**Comment by AEnterprise** [comment]
ok can you try it with this build: https://dl.dropboxusercontent.com/u/148704233/BuildCraft%20Additions/BuildcraftAdditions-1.7.10-2.0-remapTestbuild.jar

**Comment by jermangarc** [comment]
Thanks, I installed it and got the following message upon loading world: "Forge Mod Loader detected that the backup level.dat is being used. This may happen due to a bug or corruption, continuing can damage your world beyond repair or lose data/progress. It's recommended to create a world backup before continuing."

I clicked continue which ended with the crash report below.
http://pastebin.com/u5wk47P7

Here is the corresponding startup log.
https://dl.dropboxusercontent.com/u/72156241/BCA-crash-startup-log-P2.log

**Comment by AEnterprise** [comment]
ok, that didn't do a thing then but i think i found the issue: it thinks quicksilver dust is silver dust, so when remapping both items where assigned to the new silver and thus causing the issue

**Comment by jermangarc** [comment]
So is there something I can do about it? Is it a config issue?

**Comment by AEnterprise** [comment]
no it's my mistake and i have to fix it, i would sugest turning off dust registration in the config to remove all old dusts completely to fix this but i broke that feature, if you want i can easely fix that with a check and give you a custom build, then you would need to start with dissabling it in the config, loading the world once, ignore missing mappings, shut server down and turn dusts back on and launch again

**Comment by AEnterprise** [comment]
@jermangarc can you try with this version: http://ci.tterrag.com/job/Buildcraft-Additions/81/

**Comment by jermangarc** [comment]
Good news and bad news, I'm going to have to report that this as issue resolved. A new problem showed up (not a BCA issue), the same problem that showed up a few weeks back with Minechem (https://github.com/jakimfett/Minechem/issues/614). I'm going to have to ask for help in the Forge forums on this one now that the problem has come back. It sucks because at this point I can't update my map anymore because of this issue. It's like Forge ignores open slots, I don't get it. :(
