### ISSUE TITLE
Dust Code Cleaning

### ISSUE THREAD

**Issue by Speiger** [BCA-Team/Buildcraft-Additions#264]
He AEnterpriese that is not a thing to bother you.
But the Dust API is let me tell that. You copy the problem from minecraft with the IDs missmatches to it.
Instead of asking for a metadata for something you could ask in the IDust Type getID() as String,
and store them in a HashMap. That would resolve idMissmatches and you can make a lot of stuff easier. Also i would return the IDust after it got added so the getDust(ID) is not really required because peole can handle them like items/ItemStacks that represent their items.

**Comment by AEnterprise** [comment]
hmm, @iTitus wrote the new system so i guess he'll probably take a look at it, but doesn't this mean it we'll have to remap them again?

**Comment by Speiger** [comment]
The main problem is everytime a addon gets removed all dusts change their meta if they are not static set. So that is a thing which people do not like to be bound on something. (I have people i know already yell at me because you can not deinstall MC mods without distroying the world).
And with strings you can make a set ID.
^^" It is only a thing i saw while i was searching for something that could help you with another problem. xD

**Comment by iTitus** [comment]
I added the number param so that they are all static. When you remove Metallurgy (example) all the dusts would retain their meta but show 'Unknown Dust'. If you would dynamically assign metas to them based on the order of adding, everything would get messed up. One possible solution would be to save this HashMap, but this could lead to more errors and/or work.

**Comment by Speiger** [comment]
So you write the installed dusts to a file and read everything after the next start so you need to install them again? 
The thing with a hashmap was only that you are not limited on IDs and that they do not change when you exchange mods.
Maybe you should add a onRegistration(short id) so that you keep the controll with the ID system and metas do not change.

**Comment by iTitus** [comment]
They will not change because they are static

**Comment by iTitus** [comment]
Similiar to potion or enchantment IDs

**Comment by AEnterprise** [comment]
they won't change as it's always passes the meta++, no matter if the metal is present or not, closing

**Comment by Speiger** [comment]
I talk about Addon support not about stuff in BC Additions.
This thing is designt for supporting addons. But has the problems i told.

**Comment by iTitus** [comment]
It is designed like Vanilla Enchantments, with a few tweaks. Addons are supposed to choose some free IDs.
I dont say that your idea is bad or that my idea is better. Its just the approach I have gone with.
Maybe the System will be ravamped at some time in the far future.

**Comment by Speiger** [comment]
Ok. Just wanted to show the Potential Error in it.
