### ISSUE TITLE
Dusts not fully translatable

### ISSUE THREAD

**Issue by Adaptivity** [BCA-Team/Buildcraft-Additions#265]
With the new localization system for dusts, it's impossible to fully translate them -> http://i.imgur.com/IdxyFDQ.jpg the first word always stays in English.

**Comment by AEnterprise** [comment]
nope you can translate it, just localize 'Bronze', it's done this way to make it easier so i wouldn't need to do 'metal.bronze=Bronze' and that for all metals

**Comment by Adaptivity** [comment]
So, which lines I should add? "metal.bronze=Bronze" not working for me. Are you sure it's correct pattern?

**Comment by AEnterprise** [comment]
no i said i din't want to use metal.bronze and have to localize them use 'Bronze=translation'

**Comment by Adaptivity** [comment]
Oh, that's looking great. Can you show me which lines of code responds to dust localization? Since I'm not a coder and it kinda hard to me to find it. And also, https://github.com/BCA-Team/Buildcraft-Additions/blob/master/src/main/java/buildcraftAdditions/ModIntegration/ModIntegration.java#L137 this is all supported dusts(+some vanilla)? Also, you should add a note to .lang file about the dusts for other translators.

**Comment by AEnterprise** [comment]
yes those are all supported dusts, to localize the first part just localize the name of the metal (found on the lines you linked to)

**Comment by Adaptivity** [comment]
Thanks. Consider adding info about it to en_US.lang

**Comment by Adaptivity** [comment]
Ran into a problem: for two word dusts(like Black Steel, Astral Silver) I need to swap "dustname" with word "dust" but I shouldn't change other dusts. Can you do something about it?

**Comment by AEnterprise** [comment]
i'll take a look

**Comment by Adaptivity** [comment]
Hmm, I thought about it a bit more. In English all words are capitalized but in Russian only first word. So, if I swap dust and metal name, word "dust" will not be capitalized. So, I thought about better solution: Just make so if there are exist "dust.Bronze" for example, FML should skip "item.dust.name" completely. So, It will looks like "dust.Bronze=Bronze Dust" and if there are no "dust.Bronze=Bronze Dust" FML will use standard "item.dust.name".
