### ISSUE TITLE
Crash with Waila

### ISSUE THREAD

**Issue by Njet75** [BCA-Team/Buildcraft-Additions#270]
Get this crash with waila and Buildcraft additions 2.0.
Works with 1.8.4
Tested both Waila 1.5.7.a and 1.5.9 with same result.

Crash report http://pastebin.com/wGuyxbhT

/Njet

**Comment by iTitus** [comment]
Does it happen without BCA?

**Comment by Njet75** [comment]
No
Only with BCA 2.0.
Works fine without.

**Comment by iTitus** [comment]
That is very strange

**Comment by iTitus** [comment]
I am testing this now

**Comment by Njet75** [comment]
If I recall this didnt happen with Testbuild 2.0.
Gonna test this

**Comment by AEnterprise** [comment]
what's the version of waila you have installed? is it the latest one?

**Comment by iTitus** [comment]
I am testing this in my dev env with the newest WAILA (1.5.9) now

**Comment by AEnterprise** [comment]
this shouls be reported at waila's end, something is cleary going wrong but if it's something i'm doing wrong i'm not seeing what it is from this report

**Comment by Njet75** [comment]
Works with Testbuild 2.0. build 5.
Gonna wait and see iTitus result.

**Comment by iTitus** [comment]
I a dev env with some other mods there are no crashes.

**Comment by AEnterprise** [comment]
@Njet75 talked to profmobius, one of your mods (not BCA) is including an outdated version of the api

**Comment by Njet75** [comment]
Gonna look for it.
Thanks for World class support.
/Njet
