### ISSUE TITLE
Gates' conditions not functioning with KEB (3x3x3)

### ISSUE THREAD

**Issue by L00Cyph3r** [BCA-Team/Buildcraft-Additions#272]
When using the biggest KEB, and attaching  a pipe with a diamond gate, you can set certain energy-conditions (<25%, <50%, <75%, <100%, Fully charged). But these values do not correspond with the actual energy level in the KEB. Instead, the condition is always true.

See attached screenshots for further details.

![635596298334941178](https://cloud.githubusercontent.com/assets/10772371/6204651/84b33274-b553-11e4-9d45-8fb7b03c40da.png)
![635596298280142488](https://cloud.githubusercontent.com/assets/10772371/6204652/84b4da7a-b553-11e4-97bb-47b1b0a6ba50.png)

**Comment by AEnterprise** [comment]
what version of BCA are you using?

**Comment by L00Cyph3r** [comment]
BCA - 2.0
BC 6.3.6

Complete modlist screenshot:
![635596827892794355](https://cloud.githubusercontent.com/assets/10772371/6210320/aead2fa0-b5ce-11e4-8190-0d562f99f091.png)
