### ISSUE TITLE
No default extract port for Heated Furnace.

### ISSUE THREAD

**Issue by Psithief** [BCA-Team/Buildcraft-Additions#278]
Version: `BuildcraftAdditions-1.7.10-2.0.jar`

Can we please have the default side configuration be as a normal/vanilla Furnace?
That is: Output slot on bottom, the rest of the sides can be input.

This is basically so hoppers work as expected the first time it's attempted.

**Comment by AEnterprise** [comment]
you can change the configuration with the machine configurator, although i might indeed change it so that the default setting is 'both' on all sides
