### ISSUE TITLE
Is a better energy generator planned?

### ISSUE THREAD

**Issue by Jhary** [BCA-Team/Buildcraft-Additions#286]
Hello!

Is it planned to add a better "generator / engine" ? You did an awesome job with the multiblock refineries and cooling towers. What about a multiblock that needs processed fuel from the refinery and that generates a good amount of RF? Like an upgraded version of the combustion engines.

**Comment by BigXplosion** [comment]
I actually like the idea of having our own power generation (I might have mentioned it once or twice). the power generation doesn't have to be engines like BC in my opinion because I think BCA should have it's own tiering up for power generation, just like you have KEB and Furnace tiers. Also this might also be a move to run even more independent from BC or any other RF mod out there.

**Comment by AEnterprise** [comment]
this is indeed something to look intro later but for now we already have quite some things in the making and such this will probably be for 2.2 or so

**Comment by Jhary** [comment]
Nice to hear that this is being considered :)

**Comment by iTitus** [comment]
Good ideas are always welcome ;)

**Comment by AEnterprise** [comment]
it was something i though of before but it's a large project, i also don't want generators like the ones other mods have, i want new and original ones

**Comment by Jhary** [comment]
Diamonds for that AEnterprise. Would be cool to get some fresh wind regarding to that :)

**Comment by AEnterprise** [comment]
one thing i'm thinking of doing (but will require some difficult rendering trickery) is jumping like the dusters, jump on one pad and it goes down, an other one oposite to the one you jump on goes up, then you have to jump on that one, it generates a small amount of energy (3-4RF for each jump?)

**Comment by nister6000** [comment]
It would be good if Refinery would had more stuff like controller and energy input.

**Comment by AEnterprise** [comment]
i 'm thinking of making a better, more modular one but i'm gona wait with making that kind of things cause it would break all current multiblock refineries completely

**Comment by AEnterprise** [comment]
gona move this, already have other things for 2.2

**Comment by AgentK9** [comment]
I assume this is what those multiblocks are that you are posting on twitter :P

**Comment by AEnterprise** [comment]
closing, will be something for the new mod
