### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by CrazyNagaraj** [BCA-Team/Buildcraft-Additions#287]
We need to process Applied Energistics 2 Certus quartz, Nether quartz, Skystone, Flux dusts in duster. In my own pack i only have BC + addons + Railcraft + Forestry only. For early game, There is Grindstone in AE2. Railcraft rock crusher process the this dusts, but it end game machine for automation(Diamonds, steel and so much RF usage, but what if i don't install Railcraft, No automation). Please add them. Or implement AOBD2 support (I don't know, which side needs implementing. But it registers dusts for any ore from any mod).

Any planning on add flour just like AE2, 1 wheat in duster -> 1 flour in furnace -> 1 bread (useful when no AE2).

Please consider a Forestry backpack that stores any Buildcraft related(including this mod) materials, which is available when forestry is installed(like Railcraft backpacks).

**Comment by AEnterprise** [comment]
AE2 support should be doable but i need a recipe list of those recipes (and someone should let me know if any of them change), also it's something you can add yourself using minetweaker if you want

the flour i'm not so sure about doing that

the forestry backpack is something i might look intro later but that's kinda low priority atm

**Comment by CrazyNagaraj** [comment]
You are fast. I like it.
i know i can use minetweaker :)
Problem is what if a user don't know it. I think you need to implement a way, if any mod adds a ore and a dust, duster registers them. Just a suggestion. Or maybe i have to contact @ganymedes01 for duster support in AOBD2.

**Comment by AEnterprise** [comment]
i'm fast cause i saw the emails from github arrive

users don't need minetweaker knowledge, just ship the scripts with the modpack

**Comment by CrazyNagaraj** [comment]
I am not a modpack maker nor uses a modpack that is pre-made. I install what mods i like, mostly as a lot of people in Mincraft world. I talked about them. And i don't even use minetweaker much unless there is a conflict and stuff like that, because every mod is balanced in their own way, provides just enough config files. If you really interested i provide the AE2 receipes as long as i play minecraft.

**Comment by AEnterprise** [comment]
i would need the input item and output itemstack, for that i would need the gamregistry names of said items

**Comment by Speiger** [comment]
@AEnterprise JDGui & AE2-Dev for the win.
Look into the Sourcecode and find it out that take about 5-10 min.

**Comment by AEnterprise** [comment]
@Speiger i'm not home and won't be for the rest of the day, it'll be late when i return so can't do it myself atm

**Comment by ganymedes01** [comment]
AOBD would only add duster recipes for ore with matching ingots. So no certus quartz and such.
I'm still willing to add support for BCA though if @AEnterprise likes the idea :3

**Comment by AEnterprise** [comment]
@ganymedes01 you are welcome to add integration between BCA and AOBD but i'm not sure if it's needed, BCA is already adding a ton of dusts (if the metals are found) and adding the needed dusting/smelting recipes for them

**Comment by CrazyNagaraj** [comment]
Sorry for late :)

@AEnterprise Here is a receipe list for AE2 dust processing. For now i will post here, if in future recipes changes I will PM you. (Ask me if you want them in excel format, i am using libreoffice)
https://www.dropbox.com/s/58vwj1eu9s06pt0/AE2Receipes.txt?dl=0

@ganymedes01 Yea, There is no need AOBD2 support on duster, unless someone want to process Endium(Gany's End Mod) in it.

**Comment by ganymedes01** [comment]
What about other metals like metallurgy ones? Are those supported as well?

@AEnterprise Is there a way to add recipes using IMC? If not, is there an API?

**Comment by BigXplosion** [comment]
@ganymedes01, metallurgy is supported by default along with some other things ([see here] (https://github.com/BCA-Team/Buildcraft-Additions/blob/2.1.x/src/main/java/buildcraftAdditions/ModIntegration/ModIntegration.java#L139-L189)).

I've also looked into how we would go about adding dusts via IMC messages, but I might leave that to @iTitus, who wrote the whole dust items system, as I'm not really sure about how I would have to implement IMC with his system.

**Comment by iTitus** [comment]
@ganymedes01 As you can see [here](https://github.com/BCA-Team/Buildcraft-Additions/blob/2.1.x/src/main/java/buildcraftAdditions/api/item/dust/IDustManager.java#L14) the dust registration does not only require primitive types but an object, too. Currently there are two types of IDustTypes implemented (see [here](https://github.com/BCA-Team/Buildcraft-Additions/blob/2.1.x/src/main/java/buildcraftAdditions/items/dust/DustTypes.java)).
Maybe I could add two defined dust adding IMC messages like "addMetalDust" and "addGemDust" and a generic one "addDust", which requires a String which is a path to a class which implements IDustType. What do you think about that?

**Comment by iTitus** [comment]
@ganymedes01 Apart from that there is an API which you can use to add dusts and and recipes...

**Comment by iTitus** [comment]
See #291 :D

**Comment by ganymedes01** [comment]
Well since AOBD only messes with ores that have ingots (so probably only metals), the addMetalDust would be enough for me :3

But it might be easier if I just use the API and add the recipes myself, it would fit better with the system I currently have.
Unless you make a IMC method for adding recipes to the duster directly, that would be better (one less API to import XD), could take a NBT tag with an ItemStack and a String in it representing output and input respectively. But really, it's up to you guys, I'll find a way around whatever you prefer ^^

**Comment by iTitus** [comment]
For the dusting there already IMC messages: The addDusting one takes a String or a Tag as an Input and a Tag as an Output. Same for the API ;)

**Comment by AEnterprise** [comment]
closing as i think this is handled from the AEBD
