### ISSUE TITLE
Item id mismatch by an update of the world

### ISSUE THREAD

**Issue by m3gg3r** [BCA-Team/Buildcraft-Additions#290]
Hi

I get some errors with item ids when i update buildcraft on an already existing world!

The log: http://pastebin.com/G8W71SdX

Is there a possibility to update the mods without starting a new world?

Best Regards
Megger

**Comment by BigXplosion** [comment]
are you using BCA 2.0 if so try using 2.0.1 we had a fix for this.

**Comment by m3gg3r** [comment]
I'm using 2.0.1

**Comment by AEnterprise** [comment]
alright i think i know why the fix didn't work, will try to fix it later today, also can you send me a copy of the world? then i can use it to test this as right now i'm working blindly and have no way of knowing for sure if it worked or not

**Comment by m3gg3r** [comment]
Here is the world 
https://www.dropbox.com/s/ecmz8di4dad0s47/Server.zip?dl=0
ca. 503 MB

**Comment by AEnterprise** [comment]
alright i'll look at as soon as i have time

**Comment by m3gg3r** [comment]
Hi

Now i tested v2.0.2 in my world but there are still missing ids

http://pastebin.com/0Hd7e5nj

**Comment by AEnterprise** [comment]
@m3gg3r those should be safe to ignore

**Comment by m3gg3r** [comment]
Looks like everything ok

Thanks for your time and the fix
