### ISSUE TITLE
Crash with Buildcraft 6.4.1

### ISSUE THREAD

**Issue by astocky** [BCA-Team/Buildcraft-Additions#292]
http://pastebin.com/QJkHkf8K

Crash caused by Buildcraft Additions 2.0.1 with Buildcraft 6.4.1

Seems related to new programmingTable

**Comment by iTitus** [comment]
Does this happen with only BC and BCA (+ Eureka & Forge) installed?

**Comment by douchebagg8008** [comment]
no it still crashes i have same issue

**Comment by BigXplosion** [comment]
@iTitus, it is BCA who is causing the issue, I don't know how yet, maybe a wrong API version? https://github.com/BuildCraft/BuildCraft/issues/2505

**Comment by douchebagg8008** [comment]
hope it doesnt take long

**Comment by iTitus** [comment]
@AEnterprise updated the API, but I dont know if this update contains that...

**Comment by AEnterprise** [comment]
no i didn't update the api on github yet, was waiting for 6.4.1, asie told me 6.4.0 was beta and api changes where still possible, i'll update the api we ship when i get home

@douchebagg8008 and @astocky you can easely fix this by opening the BCA jar file and deleting the BC folder, that should fix it

also not sure if i'll push a fix out on the 2.0 branch, might just do a 2.1 release soonish, depends on how fast the kinetic backpack is finished, i'll hold of on finishing the eureka rewrite then

**Comment by asiekierka** [comment]
And they did happen on 6.4.1 by the way
