### ISSUE TITLE
Automatically localize dusts by checking mod's .lang files

### ISSUE THREAD

**Issue by Adaptivity** [BCA-Team/Buildcraft-Additions#293]
In continuation of #265 instead of adding dust names into BCA .lang file, it would be better to check mod's .lang files for dust names. Like it was in versions before BCA 2.0.

**Comment by AEnterprise** [comment]
i don't know to much about lang files and how MC handles them but as far as i know it takes all lang files and merges them together intro 1 larger file that contains all lang keys

**Comment by Adaptivity** [comment]
Who refactored dust code? As I say, in previous versions (before BCA 2.0) all the dust were translated correctly because they're received names from mod's .lang files. For example: If in Metallurgy ru_RU.lang present "Damascus Steel Dust" string, it uses it(https://github.com/TeamMetallurgy/Metallurgy4/blob/master/src/main/resources/assets/metallurgy/lang/ru_RU.lang#L85). This how localization worked before 2.0 but now all dusts should be translated manually, so why it needed? And as I say in #265, it's impossible to correctly translate dust names until they can be replaced by unique strings, like: "item.dust.iron.name=Iron Dust", "item.dust.diamond.name=Diamond Dust".

**Comment by AEnterprise** [comment]
blame @iTitus he refactored it, and from the  looks of it he threw out my code that made the dusts mimic dust names, i'm asigning him to him as he know the dust code best (and i already have alot of other things i'm working on atm)

**Comment by AEnterprise** [comment]
also @iTitus please fix this on the 2.0 branch (master) if possible

**Comment by iTitus** [comment]
Will look into it ASAP ;)

**Comment by iTitus** [comment]
This will be very difficult:
- Just think of TEs Tinker's Alloy Ingots. Other mods call them Bronze Ingots. Which localization should be taken?
- For some metals/gems there are no dusts. Which localization should be taken?

**Comment by Adaptivity** [comment]
This system worked before 2.0... why it's a problem now? 1) Ok, if there are both Bronze and Tinker's Alloy dusts present, pick Bronze (It's better I think). If there are no Bronze (no mods with bronze), pick Tinker's Alloy. 2) What? Isn't there are (https://github.com/BCA-Team/Buildcraft-Additions/blob/master/src/main/java/buildcraftAdditions/ModIntegration/ModIntegration.java#L137) all possible dusts? If so, well, add these names into BCA .lang file? How many metals/gems without dusts present there? With 200 mods installed, I can't find any of them.

**Comment by iTitus** [comment]
When I want a localization for our Bronze dust i would look up dustBronze in the OreDictionary, pick the first dust and take this localization. But when we add Lapis Dust (just an example) and there are no other lapis dusts in the OreDict, how should I know how to translate that?

**Comment by iTitus** [comment]
After some looking into it it will be pretty difficult and performance impacting to search for other dusts in the OreDict.
And a little clarification: Before 2.0 every dust was localized by its own.
There was for every dust: "item.dustXXXXXX.name=XXXXXX Dust".

Now there is just "item.dust.name=%s Dust" and then there need to be XXXXX=XXXX
