### ISSUE TITLE
MT Duster integration seems broken (and wrongly documented)

### ISSUE THREAD

**Issue by asiekierka** [BCA-Team/Buildcraft-Additions#302]

**Comment by iTitus** [comment]
Can you give more details please?

**Comment by BigXplosion** [comment]
@asiekierka, could you give a little more on what seems to be broken with the duster integration. Is the addition of recipes not working, or something else?

**Comment by AEnterprise** [comment]
pinging @asiekierka for mor info

**Comment by AEnterprise** [comment]
closing due to a lack of information
