### ISSUE TITLE
Kinetic Multi-Tool didnt work on Anvils

### ISSUE THREAD

**Issue by Be-Cool-Man** [BCA-Team/Buildcraft-Additions#306]
The breaking-speed is the same as you broke the anvil with bare hands

**Comment by AEnterprise** [comment]
what BCA version are you using?

**Comment by Be-Cool-Man** [comment]
2.0.2

**Comment by AEnterprise** [comment]
alright, looks like the anvil block wasn't in the list, should be fixed now
