### ISSUE TITLE
Basic Coil (BCA) eats the Heating Coil (Extra Utilities)

### ISSUE THREAD

**Issue by Be-Cool-Man** [BCA-Team/Buildcraft-Additions#307]
no description aviable, the title say all

**Comment by AEnterprise** [comment]
eats? what do you mean by eat?

**Comment by Be-Cool-Man** [comment]
The Basic Coil "eats" coal (or any kind of furnace-fuel) to heating the Furnace. aka you put one coal in the coil, the coal disapears and genertate heat to melt the ore in the Heated Furnace. That was mean by eat.

**Comment by Be-Cool-Man** [comment]
Additional information to the Heating Coil from Extra Utilities:

You can put the (fully heated) Heating Coil into an Vanilla-Furnace as fuel but it dosnt disapear, it 'loose' the stored heat during the melting-progress. If the heat is zero, you can put the coil out from the furnace and can it load/heating in any kind of an Charging Station.

**Comment by iTitus** [comment]
A simple call to getContainerItem is needed there

**Comment by AEnterprise** [comment]
@iTitus i leave the fixing of this to you then, my todo list is kinda full
