### ISSUE TITLE
Connection Bug

### ISSUE THREAD

**Issue by iTitus** [BCA-Team/Buildcraft-Additions#315]
Normal BC pipes connect to configurable dusters only when the side configuration is INPUT or BOTH.

Maybe only allow the auto-ejecting only for extraction type pipes?

**Comment by iTitus** [comment]
Intended behaviour. Any type of extraction pipe will connect to the output sides. Use those if you want to use auto-eject.

**Comment by AEnterprise** [comment]
makes no sense to limit people to using extraction pipes, it will only confuse people, they'll think they need to power the pipe/detect if there is something to pull out, ...

it also worked like this in the past so NOT inteded behaviour

**Comment by iTitus** [comment]
Ok then, will do.
