### ISSUE TITLE
Hide bcaTempFile

### ISSUE THREAD

**Issue by Adaptivity** [BCA-Team/Buildcraft-Additions#329]
Kinda minor issue but can you move bcaTempFile for example into BCA config folder?

**Comment by AEnterprise** [comment]
hmm, it should actually remove that file afther it has read it as it is no longer needed then

**Comment by Adaptivity** [comment]
I have it in .minecraft folder since forever (If I remove it, it creates again) :smile:

**Comment by AEnterprise** [comment]
it creates it each time you launch to read out the a list on github

**Comment by Adaptivity** [comment]
Also, won't create another issue for that but this line https://github.com/BCA-Team/Buildcraft-Additions/blob/0c2edf5f13873db36f2508d93d6d06001c13328b/src/main/java/buildcraftAdditions/core/EventListener.java#L52 is hardcoded. It's in the .lang file but it's not fully moved from code.

**Comment by iTitus** [comment]
I can fix the second issue in my PR

**Comment by iTitus** [comment]
Fixed by #330
