### ISSUE TITLE
coloring tool gui

### ISSUE THREAD

**Issue by AEnterprise** [BCA-Team/Buildcraft-Additions#335]
coloring tool gui needs fixing, i remember someone told me he was gona do it

**Comment by BigXplosion** [comment]
was I? could be though

**Comment by AEnterprise** [comment]
yes you said you would do it, you where gona make the texture wider and draw the buttons correctly again, i asked if you had time to do it, you said yes. This was before you started on the new multiblock system

**Comment by AEnterprise** [comment]
@BigXplosion any update on this or should i do it myself?

**Comment by BigXplosion** [comment]
tomorrow

**Comment by AlexTheGre4t** [comment]
Yeah. I changed the gui. Big_xplosion said he'd do it a while back :P
