### ISSUE TITLE
Rendering issues with the Kinetic Duster

### ISSUE THREAD

**Issue by iTitus** [BCA-Team/Buildcraft-Additions#339]
A few examples:

![Image 1](http://i.imgur.com/bhOvtJp.png)
![Image 2](http://i.imgur.com/PBL2fRB.png)
![Image 3](http://i.imgur.com/HTI9brJ.png)
![Image 4](http://i.imgur.com/RlRcWJd.png)

**Comment by AEnterprise** [comment]
i know, it's the model doing that, plenituz just didn't have time yet to update the model

**Comment by iTitus** [comment]
Just wanted to add that to our todo list that we don't forget it.
