### ISSUE TITLE
Improve Charging Station

### ISSUE THREAD

**Issue by iTitus** [BCA-Team/Buildcraft-Additions#340]
I suggest to add an empty mode, similiar to the FluidicCompressor, to empty IEnergyComtainerItems and powering RF machines/cables.

**Comment by AEnterprise** [comment]
then it's no longer a charging station, nor is this required

**Comment by iTitus** [comment]
:(

**Comment by iTitus** [comment]
It would be an Energy Interface or something like that

**Comment by AEnterprise** [comment]
maybe later
