### ISSUE TITLE
Sync bug with Fluidic Compressor in MP

### ISSUE THREAD

**Issue by iTitus** [BCA-Team/Buildcraft-Additions#341]
Occured to me in MP. If one player changes the mode on the Fluidic Compressor while another had the GUI open, too, he won't see the update.

I actually have plans on how to fix that. But that would require to change the current two buttons to one button. I wanted to discuss this fix with you.

**Comment by iTitus** [comment]
This sync bug could also appear with the Item Sorter, did not test that one though.

**Comment by iTitus** [comment]
Could also appear with the Machine Configurator.

**Comment by BigXplosion** [comment]
has to do with the container, I know how I can fix this, might have a little time to look into that tonight

**Comment by iTitus** [comment]
@BigXplosion I did not fix this as I have no idea how.

**Comment by AEnterprise** [comment]
the way to fix this is actually to send a packe't when something changes to the server who then sends an update packet to all nearby clients

**Comment by BigXplosion** [comment]
nope, there is an easier way, I'll look into it tomorrow as I have more time then

**Comment by iTitus** [comment]
The widgets need to be constantly by updated by the client TE, which gets constantly updated by the Container?

**Comment by AEnterprise** [comment]
@iTitus is this fixed now?

**Comment by iTitus** [comment]
No

**Comment by AEnterprise** [comment]
any update on this or should i fix this?

**Comment by iTitus** [comment]
As stated above: I am not able to fix this in an elegant way.

**Comment by AEnterprise** [comment]
fix is quite easy: if the button changes send a packet to the server, that then syncs to the other clients, fairly simple

i'll do it myself then

**Comment by iTitus** [comment]
Every client TE is always up-to-date, you just need to update the buttons.

**Comment by AEnterprise** [comment]
oh then it's even easier
