### ISSUE TITLE
Automatically drop installed upgrades on block destroy

### ISSUE THREAD

**Issue by iTitus** [BCA-Team/Buildcraft-Additions#343]

**Comment by AEnterprise** [comment]
isn't it doing that already?

**Comment by iTitus** [comment]
No

**Comment by AEnterprise** [comment]
refinery and cooling tower are doing that though when the multiblock invalidates, will apply something similar to the base class

**Comment by iTitus** [comment]
I already did that locally

**Comment by AEnterprise** [comment]
then pr it :p

**Comment by AEnterprise** [comment]
fixed, closing
