### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Be-Cool-Man** [BCA-Team/Buildcraft-Additions#346]
or is my ISP going crazy?

when I open
     http://www.bcadditions.tk/
I will be forwarded to 
     http://domain.dot.tk/p/?d=BCADDITIONS.TK&i=188.193.191.31&c=49&ro=0&ref=unknown&_=1427282116285

**Comment by AEnterprise** [comment]
i know, something odd is going on with the site hosting. already pinged someone for it but it isn't something that is fixed in 5 secs

**Comment by AEnterprise** [comment]
new website: http://bcadditions.ga/

now on to tracking down and updating all of them
