### ISSUE TITLE
Eureka

### ISSUE THREAD

**Issue by AgentK9** [BCA-Team/Buildcraft-Additions#350]
Tell me if I am wrong about this, but Eureka is supposed to be a core mod for many mods (possibly). Therefore, it should have either (A) a few things (By things I mean Items) e.g. research exclusive to vanilla mc or (B) no Items at all. So is there anything I can do to help bring stuff from Eureka over to BCA or something?

**Comment by AEnterprise** [comment]
eureka only has a few things and non of those can/should be ported to BCA as they are part of the eureka research system. The only things eureka adds is the engineering diary for displaying the research and research notes for unlocking research
