### ISSUE TITLE
Crash On World Load

### ISSUE THREAD

**Issue by MtnDrew** [BCA-Team/Buildcraft-Additions#352]
When I updated to 2.1.0 today, I deleted the config first per your recommendation. When I loaded my world, the game crashed. Here is a link to my crash report on pastebin. http://pastebin.com/21M6VRFa

**Comment by AEnterprise** [comment]
alright, there is no mention of BCA or any other mods in the stacktrace so i'm not sure whath heapened there, i'll pass along the report to some others and try to find the cause and fix it if it's BCA related

**Comment by AEnterprise** [comment]
afther a closer look at the crash we stumbled accross line 155:
"Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine"

could you remove optifine and try again?

**Comment by MtnDrew** [comment]
That's always there and I have no idea why. But optifine still seems to run without issues so I ignore it. Nevertheless, it's best to test it anyway. So I removed optifine and ran it again. If it helps any, here's another pastebin link. http://pastebin.com/KRtPpC23

**Comment by iTitus** [comment]
I don't know why this could crash. The Crash report points to FMLProxyPacket.processPacket(INetHandler). In this method there are a lot of try-catch-blocks and null-checks. This crash shouldn't happen.
Can you please try it with only BC, Eureka and BCA installed.

**Comment by iTitus** [comment]
(Make a backup before)

**Comment by MtnDrew** [comment]
Sorry about the wait. Pretty busy yesterday. So I removed all the mods except BC, Eureka, BCA and BuildCraftCompat, started it up and played for about 2 seconds before it crashed. The crash log for that is here, http://pastebin.com/8AN6jD56 although it might have just been a weird coincidence. Then I removed BuildCraftCompat and kept only the 3 you said and after that the game worked perfectly fine.

**Comment by AEnterprise** [comment]
ah i see the issue, you are still using eureka 2.2, you need to remove eureka (from the mods/1.7.10 folder) and install the latest one (3.0)

**Comment by MtnDrew** [comment]
Aha well that explains a lot. That was my mistake. It's working now. Thank you very much for the help and thank you for the really cool mod.

**Comment by AEnterprise** [comment]
glad you like the mods, probably should add a version thingy to prevent this in the future though
