### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by zHawky** [BCA-Team/Buildcraft-Additions#353]
Hi! thanks for update but one issue, russian language is missing
older versions have ru support, maybe you talk me where take ru lang file for replace?
(if someone asks then im trying to reload language from en to ru and backward)

**Comment by iTitus** [comment]
Calling @Adaptivity...

**Comment by Adaptivity** [comment]
It's impossible. It's still here: https://github.com/BCA-Team/Buildcraft-Additions/blob/2.1.x/src/main/resources/assets/bcadditions/lang/ru_RU.lang and Eureka here: https://github.com/BCA-Team/Buildcraft-Additions/tree/2.1.x/src/main/resources/assets/eureka/localizations/ru_RU
It's probably problem on your local setup. But I'll check it right now.

**Comment by zHawky** [comment]
Well just now tested Deutch, same problem :\

**Comment by AEnterprise** [comment]
if other languages also don't work it's a problem with your local setup i think

**Comment by zHawky** [comment]
well in other mods work correctly, steampower, mekanism, even original buildcraft..

**Comment by Adaptivity** [comment]
Working fine for me. Just tested.

**Comment by zHawky** [comment]
But anyway im experiencing that problem only in two mods, there are magicbees and buildcraft additions, not critical..

**Comment by Adaptivity** [comment]
As I say: check your local setup. It's not magic bees or BCA problem.

**Comment by Adaptivity** [comment]
Seems I found it: only Eureka translation not working for you? Because for me it doesn't working.

**Comment by zHawky** [comment]
Ну если моды работают то значит я верно их поставил так?

**Comment by Adaptivity** [comment]
Да, новая система локализации не работает. Затронут только дневник. @AEnterprise @iTitus confirmed that engineering diary translation not working.

**Comment by AEnterprise** [comment]
@Adaptivity that's cause it needs updating to the new lang system, you updated it for eureka but not for BCA

**Comment by Adaptivity** [comment]
I'm half updated it. But even updated text still in English. You can check it yourself.

**Comment by AEnterprise** [comment]
euh, what is the russian one in the list? there are a few things in the list that have characters that i can't read

**Comment by Adaptivity** [comment]
http://i.imgur.com/A6Ov737.jpg

**Comment by AEnterprise** [comment]
oh i found the error, derpy me, one sec please

**Comment by AEnterprise** [comment]
fixed, will probably do new eureka release in a few days

**Comment by zHawky** [comment]
Well, appreciate for your feedback, thanks.
