### ISSUE TITLE
Two %s tags can't be swapped

### ISSUE THREAD

**Issue by Adaptivity** [BCA-Team/Buildcraft-Additions#355]
This tooltip -> https://github.com/BCA-Team/Buildcraft-Additions/blob/2.1.x/src/main/resources/assets/bcadditions/lang/en_US.lang#L179 contains two %s tags and they're can't be swapped. Perhaps you should change one of them and this solve the problem.

**Comment by AEnterprise** [comment]
why should they be swapable?

**Comment by Adaptivity** [comment]
I want to change it to format like: *Currently stores: Molten Copper (2000 mB)*

**Comment by AEnterprise** [comment]
hmm, that might actually be a better format then what we have now, calling @iTitus and @BigXplosion for opinions

**Comment by Adaptivity** [comment]
You can use old format for English. I'm only need to change it in Russian because it's a bit ugly in this old format.

**Comment by AEnterprise** [comment]
alright, just gona wait on the others opinions first though, not gona release 2.1.1 in the next few days anyways unless something major pops up

**Comment by iTitus** [comment]
They can be swapped

**Comment by BigXplosion** [comment]
sure
