### ISSUE TITLE
Can't place semi automatic duster without it to break

### ISSUE THREAD

**Issue by Shayleel** [BCA-Team/Buildcraft-Additions#358]
Hi, I can’t place the semi automatic duster without it to break even if I have done the processing required with the basic duster and got the “Eureka” in the chat.
I also tried by giving myself the research notes but it still not working.

**Comment by AEnterprise** [comment]
odd, never heapened to me in testing, will investigate

**Comment by AEnterprise** [comment]
did you get the eureka message before or afther you updated your eureka?

**Comment by Shayleel** [comment]
It is a new installation of Buildcraft addition and Eureka, so after I installed the latest versions.
I also tried in a new world and it did the same.

**Comment by AEnterprise** [comment]
so BCA and eureka are the only mods installed?

**Comment by Shayleel** [comment]
No, I'm using this mod list : http://pastebin.com/javDiC1F

**Comment by AEnterprise** [comment]
quite a big list, could you make a new world and try it there with only BC, BCA and eureka installed?

**Comment by Shayleel** [comment]
I just tried it and still the same issue

**Comment by xenexelen** [comment]
I have the same issue with only BC 6.4.6, BCA 2.1.0 and Eureka 3.0
In Creative no problem - in Survival the semi automatic duster break after research

**Comment by Shayleel** [comment]
Also, when it break, I receive 1 gold ingot, 3 stones and 4 golden transport pipes, don't know if it's intended or not.

**Comment by AEnterprise** [comment]
found the issue, derped up a few things in the update to eureka 3.0
