### ISSUE TITLE
Crash on assembly table assembling drill head

### ISSUE THREAD

**Issue by TheLoneWolfling** [BCA-Team/Buildcraft-Additions#359]
It seems reproducible - just dump a *single* iron ingot, gold ingot, and tool core, tell the assembly table to make a drill head, and wait for it to craft. Crashlog is [here](http://pastebin.com/sCrzZFf2) - but the relevant section is below also.

This probably also causes crashes with other recipes that require multiples of a single item, although I haven't checked yet.

It seems like the assembly table doesn't handle your method of registering recipes that require multiples of a single item well. Not surprising, considering that BC itself doesn't have any assembly table recipes that require multiple of a single item.

    java.lang.NullPointerException: Ticking block entity
    	at buildcraft.silicon.TileAssemblyTable.func_145845_h(TileAssemblyTable.java:99)
    	at net.minecraft.world.World.func_72939_s(World.java:1939)
    	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

This implies that something [here](https://github.com/BuildCraft/BuildCraft/blob/6.4.x/common/buildcraft/silicon/TileAssemblyTable.java#L99) is null - either `currentRecipe` is null (not possible due to the proceeding null check), or `currentRecipe.craft(<TileAssemblyTable>, false)` is null, or `currentRecipe.craft(<TileAssemblyTable>, false).crafted` is null. Either way, the fault lies with `currentRecipe`. `currentRecipe` is an `IFlexibleRecipe<ItemStack>`. So we jump there. 

From `IFlexibleRecipe<ItemStack>`, we jump to `FlexibleRecipe<ItemStack>`. (It could be something else implementing `IFlexibleRecipe<ItemStack>`, but as far as I can tell there aren't any.

There are two cases:

First, for `IFlexibleRecipe<ItemStack>.craft(<TileAssemblyTable>, false)` ([here](https://github.com/BuildCraft/BuildCraft/blob/6.4.x/common/buildcraft/core/recipes/FlexibleRecipe.java#L98)) to be null. This implies that one of the requirements are not met. (Well, duh?). So I'm going to assume that's the case.

Then the question becomes: why wasn't it caught earlier? Or rather: why did `currentRecipe.canBeCrafted(<TileAssemblyTable>)` return `true`? And the answer seems to lie [here](https://github.com/BuildCraft/BuildCraft/blob/6.4.x/common/buildcraft/core/recipes/FlexibleRecipe.java#L183) - namely that, when it's in the "preview" stage, it doesn't actually decrement anything. So it sees the three different stacks of one iron ingot each, checks "is there at least one iron" 3x, which there is. So it thinks it can craft it when it actually cannot.

The fix, it would seem, would be to [here](https://github.com/BCA-Team/Buildcraft-Additions/blob/90397f6426e9759ecaf7be90ccbce67338be6873/src/main/java/buildcraftAdditions/reference/ItemsAndBlocks.java#L564) change the repeated strings to one itemstack for each item, containing the multiples. Though, that being said, that would mess up ore dictionary integration, if that matters. It may be better to build your own list of alternatives with OreDict.getOres.

Hopefully this gets fixed - as is it's rather hampering my attempts at automating my assembly tables. Occasionally there's a delay in one of the inputs and it crashes the game, not fun.

**Comment by TheLoneWolfling** [comment]
Welp, the world is now crashing on load with the same error. Of course it is - it saved partway through the assembly table crafting the broken recipe.

**Comment by TheLoneWolfling** [comment]
"Fixed" it for now by enabling Forge's "remove crashing tile entities" mode.

**Comment by TheLoneWolfling** [comment]
For now I'm working around it with the following lines in MineTweaker:

    mods.buildcraft.AssemblyTable.remove(<bcadditions:toolUpgradeDrill>);
    mods.buildcraft.AssemblyTable.addRecipe(<bcadditions:toolUpgradeDrill>, 1000, [<ore:ingotIron>, <ore:ingotGold>, <bcadditions:toolCore>]);
    mods.buildcraft.AssemblyTable.remove(<bcadditions:toolUpgradeHoe>);
    mods.buildcraft.AssemblyTable.addRecipe(<bcadditions:toolUpgradeHoe>, 1000, [<ore:ingotIron>, <ore:ingotGold>, <bcadditions:toolCore>]);
    mods.buildcraft.AssemblyTable.remove(<bcadditions:toolUpgradeChaisaw>);
    mods.buildcraft.AssemblyTable.addRecipe(<bcadditions:toolUpgradeChaisaw>, 1000, [<ore:ingotIron>, <ore:ingotGold>, <bcadditions:toolCore>]);
    mods.buildcraft.AssemblyTable.remove(<bcadditions:toolUpgradeDigger>);
    mods.buildcraft.AssemblyTable.addRecipe(<bcadditions:toolUpgradeDigger>, 1000, [<ore:ingotIron>, <ore:ingotGold>, <bcadditions:toolCore>]);

Not pretty, and changes the balance slightly (3 iron and 2 gold to one of each.), but at least prevents the crash.

**Comment by AEnterprise** [comment]
@TheLoneWolfling thanks for the clear bug report and all the investigating you have done so far.
enabeling the "remove crashing tile entities" does prevent the crash but also will mean you can lose stuff, so i sugest turning it off again as it might mask other crashes in the future so they won't get fixed

calling @asiekierka for this as i think this is a BC bug, i think this heapens cause the iron rod is made using one iron ingot and the recipe detection fails due to that overlap in the recipe

**Comment by asiekierka** [comment]
This is a very neat crash report! I'll investigate it today

**Comment by AEnterprise** [comment]
BC  issue, should be fixed
