### ISSUE TITLE
Getting an NPE when i fire the Portable Laser without Eureka-Research (in Survival-Mode)

### ISSUE THREAD

**Issue by Be-Cool-Man** [BCA-Team/Buildcraft-Additions#360]
Link to OpenEye:
http://openeye.openmods.info/crashes/0f5e299856d84196a6671dc492d58065

**Comment by AEnterprise** [comment]
is actually an eureka issue not BCA, will still look intro fixing it

**Comment by AEnterprise** [comment]
should be fixed
