### ISSUE TITLE
Build script doesn't work

### ISSUE THREAD

**Issue by Xee1** [BCA-Team/Buildcraft-Additions#363]
Hi @AEnterprise , I tryed to run gradlew, but this error happen:
****************************
 Powered By MCP:
 http://mcp.ocean-labs.de/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : unknown
****************************

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':test'.
> Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 11.662 secs

**Comment by AEnterprise** [comment]
what is the commad you ran to excecute it and what are you trying to do?

**Comment by Xee1** [comment]
I'm doing gradlew build simply @AEnterprise , I'm trying to build the mod.

**Comment by AEnterprise** [comment]
did you do:
```
git submodule init
git submodule update
```

**Comment by Xee1** [comment]
@AEnterprise  Oh, no, I only did gradlew build, sorry.
then I do : 
git submodule init
git submodule update
gradlew build ?
Sorry but with submodule I'm very bad.

**Comment by AEnterprise** [comment]
yeah that should work if you are on windows and have gradle installed, also why are you trying to compile the mod yourself and not just downloading compiled versions?

**Comment by Xee1** [comment]
For the annoying bug that I reported yesterday, just to test if it works

**Comment by AEnterprise** [comment]
i tested it and it works don't worry, new release comming probably tomorow so if you're not a coder save yourself the trouble of setting it all up to compile

**Comment by Xee1** [comment]
Thanks for all @AEnterprise , keep it up that awesome mod!

**Comment by AEnterprise** [comment]
i will :)
