### ISSUE TITLE
Minetweaker support + Dusters errors

### ISSUE THREAD

**Issue by Lathanael** [BCA-Team/Buildcraft-Additions#365]
In reference to #302 !!

- It seems like the Minetweaker Support is wrongly documented
  Trying the command from this link
  http://bcadditions.ga/?page_id=605
  results in MT to error:
  https://gist.github.com/Lathanael/47056e76d86964469fb4
  Upon inspecting the code here on GitHub i found the correct syntax:
  ```
  mods.bcadditions.dusters.<function>
  ```

- It also has some bugs(using the updated syntax):
  - Ore Dict support missing:
   Trying to remove all recipes with cobblestone with
    ```
    mods.bcadditions.dusters.removeDusting(<ore:cobblestone>);
    ```
    the following error occurs:
    ```
    [19:16:13] [Client thread/INFO]: [CHAT] ERROR: BuildCraftAdditions.zs:60 > a method available but none matches the parameters (minetweaker.oredict.IOreDictEntry)
    ```
  - Upon removing one script line and trying to reload the file i get the following error:   https://gist.github.com/Lathanael/ec95f115459553b07e6a
  The first is after trying the reload command and the 2nd after trying to load up the world after leaving it.

**Comment by AEnterprise** [comment]
alright @iTitus renamed them (why is something i don't know) and the documentation wasn't updated
i'll keep it like this to not break working scripts again

there is no oredict support yet no, i'll look intro adding that

don't reload MT scripts that involve BCA for now, it'll try to remove the recipes again or add them a second time


and thanks for the clear bug report (and the reference to the old issue) asie opened that but never explained what was wrong, at the time i had no time to investigate and he refused to give further information so i closed it

**Comment by AEnterprise** [comment]
wiki updated

**Comment by Lathanael** [comment]
I suspected as much for the removal. My only concern is what happens if you switch servers with different settings for BCA. It might or might not crash your client as MT rolls back recipes before applying the new ones from the 2nd server(AFAIK). I currently can't verify that is my machine isn't capable of running 2 servers and 1 client.
___
The ore dict support would be a really nice-to-have feature. Thank you :)

Another thing to look at while you are already at it is maybe extending the support(for dusters) a bit by adding a function similar to the furnace recipe removal from MT:
```
furnace.remove(<*>, <bcadditions:dustIron>);
```
This should remove any recipe which has iron dust(s) as an output. Having such a function might be handy if you got multiple ores which have the same output as it would reduce the amount of script lines from x(amount of ores) to one.

But the ore dict and removal are just suggestions. The crashes/errors are more important imo.
___
And no need to thank me for the clear report. I code myself. I know how it is when someone comes to you and just says "It's broken, fix it" without giving ANY hint on what is broken and no steps to reproduce the error.

**Comment by AEnterprise** [comment]
hmm, these are enhancements that would indeed be usefull, as you can see the crashes have been handled and oredict suppport has been added (open PR) maybe @iTitus can add these other things as well to it or do one of us will do it later

and asie is also codes but his bug report didn't contain any hint on what was broken and clear bug reports are kinda rare

**Comment by iTitus** [comment]
Fixed everything in my PR. Reloading will work again and OreDict duster recipes via MT work perfectly.

Sadly it is not possible to remove recipes with a given output. This is caused by the layout of our recipe system.
What you can do is removing via OreDict:
mods.bcadditions.removeDusting(<ore:oreCopper>);
This will remove every recipe which has an itemstack as a valid input which is registered in the OreDict as oreCopper.

**Comment by AlexTheGre4t** [comment]
Very nice to see this fixed. I ran into one or two little problems like this yesterday but I couldn't reproduce them

**Comment by AEnterprise** [comment]
fixed
