### ISSUE TITLE
Infinite Fuel Problem

### ISSUE THREAD

**Issue by MtnDrew** [BCA-Team/Buildcraft-Additions#371]
Alright, so I have no idea what I did, but I set up my fuel refinery last night, powered it up and now it just keeps producing fuel. The reservoirs of oil and fuel gas in the refinery are not depleting, and the reservoirs of fuel gas and fuel in the cooling tower are also seemingly infinite. I know having as much fuel as you could ever need is the Minecraft dream, but I do like the challenge of having finite resources. If it helps at all, I did use Thermal Expansion's Magmatic Dynamo to power it and Portable tank to fill it with oil. (I do have about 140 mods installed, so it could just be an issue of too much modding.)

**Comment by AEnterprise** [comment]
hmm, will do a test of this to verify

**Comment by iTitus** [comment]
Any upgrades installed?
