### ISSUE TITLE
Multi tool

### ISSUE THREAD

**Issue by ryuben** [BCA-Team/Buildcraft-Additions#372]
Got 3 tier 3 caps in it - it won';t charge past 1mill RF (one was charged when it and 2 tier 1 caps lived in the tool)

it shows 1/3mill rf - lasers hit the table but no power is going into the tool

Took the caps out and they charged fine by them selves and the tool accepted them in and show 3mill RF stored

**Comment by AEnterprise** [comment]
just took a new tool, put 3 diamond capsules in it and it charged completely just fine in both the charging station and the charging table
