### ISSUE TITLE
Suggestion: Computer controlled Sort-O-Tron

### ISSUE THREAD

**Issue by Lathanael** [BCA-Team/Buildcraft-Additions#374]
As i already mentioned on Twitter, but i though maybe an "Issue" isn't the worst idea so nobody forgets it :) You can close it and i would be fine with it if you do not want the suggestion as an Issue.
Basically this would be a replacement for the RP2 Sortron.
_____________
Some integration of OC and CC to the Sort-O-Tron would be nice. Either build into the existing one or as a new block.

Here's a list of Functions the computer might be able to control with the block connected:
##### Inline:
* Inline colour control (ie. the computer controls what color an item gets when it passes through the block)
* Output direction control (like diamon pipe)

##### As a pipe entry point(ie. adjecent to inventories):
* Pull requested item and amount from Inventory (using power maybe?)
* Colour the requested Items (Like the current Sort-O-Tron)
* Define Output side 

This list is by all means not what the computer HAS to be able to do. It is just a some points i find interesting. And its not complete so others might come up with more ideas.

**Comment by AlexTheGre4t** [comment]
A more advanced Sort-O-Tron is coming. Not sure when though due to big_Xplosion being gone for the past week or so. No word on him on when that's being implemented and what features it will have yet :)

**Comment by iTitus** [comment]
It's a secret :P


> Am 08.04.2015 um 20:04 schrieb Alex Bilbie <notifications@github.com>:
> 
> A more advanced Sort-O-Tron is coming. Not sure when though due to big_Xplosion being gone for the past week or so. No word on him on when that's being implemented and what features it will have yet :)
>

**Comment by BigXplosion** [comment]
yeah... all the knowledge about it is gone when I vanished... (vanishes again until he properly has time)

**Comment by AEnterprise** [comment]
pinging @BigXplosion

**Comment by Lathanael** [comment]
Seems like @BigXplosion is vanished in a big explosion :P

**Comment by BigXplosion** [comment]
no @Lathanael I was away for a week (again) due school and scouting reasons, this is on the todo list but I did some little improvements and additions to the code at first and also with the exams coming up this might not be for 2.2 but I'll try my best

**Comment by AEnterprise** [comment]
closing, will be something for the new mod
