### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by iTitus** [BCA-Team/Buildcraft-Additions#378]
I suggest the introduction of achievements to BCA.
I need your suggestions for basic and special achievements.

I know that the concept of "Craft XXX" or "Build YYY" is included in Eureka, but achievements would be a nice thing to have,
I am putting this here for discussion.

**Comment by AEnterprise** [comment]
what's the status on this?

**Comment by iTitus** [comment]
We can merge this first batche once I aligned it to the branch
