### ISSUE TITLE
Clay Mixer

### ISSUE THREAD

**Issue by iTitus** [BCA-Team/Buildcraft-Additions#379]
A basic block that is capable of mixing water and sand together to produce clay.
Maybe with a neat animated model :P

**Comment by AEnterprise** [comment]
why would we need this?

**Comment by iTitus** [comment]
Because it is cool :P
Clay mixing with this machine would be a low tech alternative for clay searching. It would take a lot of water and time to make clay.

**Comment by iTitus** [comment]
Maybe it could even have tiering like the dusters.

**Comment by AEnterprise** [comment]
not to fond of this idea, not realy exciting/original/usefull

**Comment by iTitus** [comment]
That's why I opened this thread here so that everyone can contribute.

**Comment by AEnterprise** [comment]
not gona add this at this time
