### ISSUE TITLE
Discharging Station

### ISSUE THREAD

**Issue by iTitus** [BCA-Team/Buildcraft-Additions#380]
Either an additional mode for the Charging Station or a completely new block.
It should be capable of pulling RF out of any RF container in item form and providing that energy.

**Comment by AEnterprise** [comment]
i don't know cases where this would be usefull

**Comment by iTitus** [comment]
That's why I opened this thread here so that everyone can contribute.

**Comment by TheLoneWolfling** [comment]
It would be useful for me, at least. There are far too many times I'm left with a slightly-charged item that as a result doesn't stack.

**Comment by AEnterprise** [comment]
sounds a bit OP to me, closing for now unless someone can convince of usage for this
