### ISSUE TITLE
After update to v.2.1.1 getting hint for a newer version of BCA (v.2.1.0)

### ISSUE THREAD

**Issue by Be-Cool-Man** [BCA-Team/Buildcraft-Additions#381]
After updating to version 2.1.1 I get every time when loading a world the message that there is a new version of BCA:
[Quote]
There is a newer version of BuildCraft Additions aviable (2.1.0) Please consider updating.
[/Quote]

**Comment by AEnterprise** [comment]
oh my bad, forgot to push to the master branch, fixed now
