### ISSUE TITLE
java.lang.IllegalStateException: Already tesselating! 2.1.1

### ISSUE THREAD

**Issue by SvEgiiVEteR** [BCA-Team/Buildcraft-Additions#382]
just not sure whether your mode problems, but when generated Powerplant and if flying or going near it 30 seconds then immediately crash the client. sometimes after 5 seconds.
and it is connected with OptiFine_1.7.10_HD_U_B5 as if to remove the error disappears.
If this is not your mod ... what do I do to find out how to find out?
thank you.
PS
long searched for the cause ... difficult to catch the bug. on this and am writing to you, as though some sort of clue ..
http://paste.ubuntu.com/10804696/
sorry for bad english

**Comment by AEnterprise** [comment]
i'm sorry but there is nothing i can do about this nor can i track this down further. As you said it goes away with removing optifine and sadly optifine is know for messing with rendering and causing rendering issues.

The log you provided also doesn't narow it down, it shows that the error is from rendering an item on the ground, pure vanilla methods stacktrace

so i'm sorry but i can't help with this and i don't think anyone realy can, the only thing you can do is report it to optifine and maybe they can try to fix it but i'm not completely sure about that

**Comment by lukxx** [comment]
I've been trying to fix this issue for a week, sadly the only solution to fix this, is to remove optifine... I will report it to optifine forum page.

**Comment by AEnterprise** [comment]
yeah sorry i can't help with this but as optifine is messing with the rendering there is nothing i can do

**Comment by SvEgiiVEteR** [comment]
now the problem is gone again ... weird ... then it does not exist, then swoops down like locusts. tested more than once.

**Comment by AgentK9** [comment]
Sometimes this happened to me when I go near a village w/o optifine.
