### ISSUE TITLE
Support for Fortune ores

### ISSUE THREAD

**Issue by AgentK9** [BCA-Team/Buildcraft-Additions#386]
Just a nice to have for anyone who uses this mod: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292510-fortuneores

**Comment by iTitus** [comment]
What do you mean with support?

**Comment by AgentK9** [comment]
Never mind. The heated Furnace runs off of vanilla recipes, right?

**Comment by iTitus** [comment]
Yes it does ;)

**Comment by AgentK9** [comment]
maybe, a bit OP, but support in dusters?

**Comment by AEnterprise** [comment]
doubeling already doubled ores is indeed kinda OP, not a good idea for BCA if you want to do that use minetweaker or so to do that
