### ISSUE TITLE
Kinetic duster animation passes through blocks below it

### ISSUE THREAD

**Issue by AndyF21** [BCA-Team/Buildcraft-Additions#387]
When processing ores in the kinetic duster, the animation passes through the floor and into the room below it.  It could just be the way that Minecraft renders animations or it could be my setup for all I know, but I felt the need to bring it up.  The "dust waterfall" that spews out of the duster seems a little excessive (reaches 4 or 5 blocks below it).  If the "bleed-through" effect can't be helped, would it be possible to reduce the animation from moving more than a single block away from the duster?  I appreciate the time and effort that went into creating the animation (looks great BTW), but IMO it would look much better if the effect was reduced.  Thanks for hearing me out.  :)

![duster animation](https://cloud.githubusercontent.com/assets/11947886/7201864/5391d568-e4da-11e4-8119-dec486437116.jpg)

**Comment by iTitus** [comment]
We are using MCs standard block-breaking animation. If that derps up we cannot do anything about that. A new particle type would be an option.

**Comment by iTitus** [comment]
Are the duster particle effects affected by the MC particle setting?

**Comment by AndyF21** [comment]
Just tested it.  Yes, setting particles to "minimal" removes the duster animation (as well as most other particle effects).

**Comment by iTitus** [comment]
Thanks for testing.

**Comment by AEnterprise** [comment]
yeah this is MC stuff but maybe a config option on our side might help

**Comment by AndyF21** [comment]
Thanks!  :)

**Comment by AEnterprise** [comment]
no problem, you will need to wait for the 2.2.0 release though
