### ISSUE TITLE
Cant join my modded server with BCAdditions installed

### ISSUE THREAD

**Issue by PancakeCandy** [BCA-Team/Buildcraft-Additions#390]
Server Log:
https://db.tt/HPwpu5SB

Client Log:
https://db.tt/vTumYGv1

Upon joining it comes up with a fatally missing blocks error upon removing BCAdditions from both the server and client it works again.

Used Dropbox instead of pastebin since these logs are massive.

**Comment by iTitus** [comment]
Does this happen again if you try to connect to the server a second time?

Is there a screen with a yes/no-option asking you to confirm the joining?
If there is one you have to click the 'yes' button

**Comment by AEnterprise** [comment]
are you sure both the client and server have the same version of BCA and the same configs?

**Comment by PancakeCandy** [comment]
@iTitus Yes no matter how much i try i get the same error there is no confirm option coming up
@AEnterprise Yes Versions match Perfectly I even tried to copy my Bcadditions config to the server folder to match the configs perfectly but still not working

**Comment by AEnterprise** [comment]
hmm, i do see you are running a bukkit server, that might be the only thing causing this issue then :/

**Comment by PancakeCandy** [comment]
@AEnterprise I really prefer running on Cauldron which is bukkit combined with forge. But i could give forge's own server files a try see if that will work if it does its really a issue with cauldron

**Comment by PancakeCandy** [comment]
@AEnterprise Tested with vanillia forge server Seems to be working perfect with the newest version
So yup that clearly much proves that its not working on a cauldron server only on vanillia forge.
Anyway i will be taking the mod temporary out of the cauldron server until I found a proper solution to the problem. For now i have to use vanillia forge i guess. Thanks for your help anyway

**Comment by AEnterprise** [comment]
yeah, sorry that it doesn't work for you but there is nothing i can do about it :/
