### ISSUE TITLE
Can't create a new world

### ISSUE THREAD

**Issue by Xee1** [BCA-Team/Buildcraft-Additions#397]
Hi @AEnterprise , with BCA 2.1.2 Eureka 3.0.2 and BuildCraft 6.4.13 I've got this when I try to create a new world:
https://gist.github.com/Xee1/8bede32379cee8b25d2e
And the world isn't created.
This when I try to set:
    B:shouldRegisterDusts=true to false
Sorry for bad english.

**Comment by AEnterprise** [comment]
hmm, seems like i asumed gilded red metal dust would always be registered

**Comment by iTitus** [comment]
Hmm, maybe I should add an option to dust types to allow to force the registration.

**Comment by AEnterprise** [comment]
yeah that's what i was thinking

**Comment by iTitus** [comment]
I think that this won't work because the config option prevents any dusts from being registered and so the IDustType function won't even get called.

**Comment by AEnterprise** [comment]
whell i created a new world with the dust registration config option turned off and it worked
