### ISSUE TITLE
Strange symbol in charge and fluid tooltips

### ISSUE THREAD

**Issue by Adaptivity** [BCA-Team/Buildcraft-Additions#398]
I saw this in many mods previously. And now in BCA... Screenshots: http://i.imgur.com/Al1jqvl.jpg http://i.imgur.com/Mx3y5WX.jpg I'm on BC 6.4.13 and BCA 2.1.2.

**Comment by AEnterprise** [comment]
alright that's very odd, no idea what could be causing that

**Comment by iTitus** [comment]
Congratulations Java, you don't know the number separator in Russian.

**Comment by Adaptivity** [comment]
Russian? I've tested it on English...

**Comment by iTitus** [comment]
Java tries to fill in the Number separators for your language. 
Commas for English, dots for German etc.

**Comment by Adaptivity** [comment]
I only can say that this problem was in Ender IO and it was fixed. But I can't find neither issue or commit which fixed it. But as I can see, they just removed commas from numbers...

**Comment by AEnterprise** [comment]
java issue, nothing we can do about it from our end :/
