### ISSUE TITLE
Crash with latest buildcraft

### ISSUE THREAD

**Issue by Xee1** [BCA-Team/Buildcraft-Additions#400]
Hi @AEnterprise , with latest buildcraft I get this crash https://gist.github.com/Xee1/68625fd033695a7c2d70
Andt his error in console:
https://gist.github.com/Xee1/462d8cd643727249df07
BCA 2.1.3
Buildcraft 6.4.14

**Comment by BigXplosion** [comment]
BCA 2.1.3 is for BC 7 beta versions

**Comment by Xee1** [comment]
Oh, I haven't noticed. Sorry about that.
