### ISSUE TITLE
Crashed to desktop trying to open a KEB

### ISSUE THREAD

**Issue by misterfixit** [BCA-Team/Buildcraft-Additions#405]
https://www.dropbox.com/s/e99x4irppwwgsw5/crash-2015-05-08_20.36.04-client.txt?dl=0

**Comment by AEnterprise** [comment]
should be an easy fix

**Comment by AEnterprise** [comment]
hmm, seems like the only thing that would cause this crash is an KEB with a capacity of 0, that would probably be caused by a setting in your configs or something messed with the keb NBT data

**Comment by AEnterprise** [comment]
@misterfixit any update on this?

**Comment by misterfixit** [comment]
I haven't run into the issue recently but the KEB defenitely did not have a capacity of 0

**Comment by AEnterprise** [comment]
does it still heapen or was this a one time occurance?

**Comment by AEnterprise** [comment]
found the bug

**Comment by AEnterprise** [comment]
should be fixed

**Comment by misterfixit** [comment]
thanks sorry I couldnt be of much help it was very random it seemed
