### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Noobsloth** [BCA-Team/Buildcraft-Additions#407]
http://pastebin.com/yitWuVEJ

**Comment by leSamo** [comment]
BCA 2.1.3 requires BC 7, you are using BC 6.4.14. http://mod-buildcraft.com/buildcraft-703-beta-compat-700-beta.html.

**Comment by leSamo** [comment]
protip: usually NoClassDefFoundError means, that you are missing a mod that other mod depends on, or they are not compatible.

**Comment by AEnterprise** [comment]
indeed, i should have put this in the mod annotation so forge detects it and shows an error instad of crashing

**Comment by iTitus** [comment]
This is included in my PR ;)
