### ISSUE TITLE
Recipes don't use the Ore Dictionary

### ISSUE THREAD

**Issue by Xee1** [BCA-Team/Buildcraft-Additions#408]
Hi, all recipes doesn't use ore dictionary for gear, in fact, I can only use gear for BuildCraft, and for example not from ThermalExpansion.
Ore dictionary for gears are:
gearGold
gearIron
gearStone
gearDiamond
gearWood

**Comment by AEnterprise** [comment]
for gona keep it that way, need to tackle the recipes for 2.2 anyways, some are gona change to be less dependant on specific BC items

**Comment by AEnterprise** [comment]
done in https://github.com/BCA-Team/Buildcraft-Additions/commit/fd80fb810fa815573d4b48d3da7e7f047efedf40

**Comment by Xen1** [comment]
Thanks!
