### ISSUE TITLE
Client crashes by opening Cooling Tower GUI.

### ISSUE THREAD

**Issue by BlackYamato** [BCA-Team/Buildcraft-Additions#409]
Client crashes by opening Cooling Tower GUI.
It happens in the multiplayer.
It seems that does not occur in a single play.
Please fix.

Environment:
・Minecraft 1.7.10
・Minecraft Forge 10.13.2.1291
・BuildCraft 6.4.8 (This is the latest version corresponding to the Forge 1291.)
・BuildCraft Compat 6.4.2
・BuildCraft Additions 2.1.2
　etc.

Client Crash Report
・http://pastebin.com/jkTeDHDb

**Comment by AEnterprise** [comment]
you need to update your forge and BC, the crash comes from recent forge fluid changes that are not compatible with older forge builds, so you need to upgrade forge or downgrade BCA
