### ISSUE TITLE
Server wont boot with bca 2.1.3

### ISSUE THREAD

**Issue by TheMrCaveman** [BCA-Team/Buildcraft-Additions#410]
Server crash with BCA 2.1.3

http://pastebin.com/cLRVPtWZ

**Comment by iTitus** [comment]
BCA is not (yet) compatible with BC 7.0.4, try 7.0.3 or wait for an update of BCA.

**Comment by AEnterprise** [comment]
need to talk to asie, told me this stuff wouldn't realy change anymore, also saw him say on irc that 7.0.4 further broke things

**Comment by AEnterprise** [comment]
alright, the integration table api changed (again) but this should be the final one, will update to it when i get home and do a new release (might see about some other minor things as well)

**Comment by TheMrCaveman** [comment]
thanks  A lot!
