### ISSUE TITLE
Kinetic Multi-tool

### ISSUE THREAD

**Issue by AgentK9** [BCA-Team/Buildcraft-Additions#412]
I downloaded Chilm's World on curse, and whenever I right-click the tool on thin air, it disapears.

Mods:
BC 7.0.2
BCA 2.1.3
Railcraft 9.6.0.0
DoggyStyle 1.0.5.78
damageIndicators
Mine and Blade: BattleGear 2
Adventure Backpack
BiblioCraft
BCcompat
Carpenter's Blocks
CodeChickenCore
DenseOres
dungeonpack
ender storage
Eureka 3.0.2
Finder Compass
Ganys Surface
Inventory tweaks
Iron chest
Jabba
JourneyMap
NEI
OpenBlocks
OpenModsLib

If versions are needed, I will happily provide them

**Comment by AEnterprise** [comment]
did you unlock the research for it?

**Comment by AgentK9** [comment]
oooooooooooooooooooooooooooooooooooooooohhhhhhhhhhhhhh... I might reopen this if that doesn't work

**Comment by AgentK9** [comment]
I forgot about that
