### ISSUE TITLE
Crashing to desktop

### ISSUE THREAD

**Issue by critaL** [BCA-Team/Buildcraft-Additions#413]
Here is the crashlog 
http://pastebin.com/TfcW19Z1

I have no idea what im doing wrong or how to fix it since this is my first time dabbling with custom modpacks. I have the latest Buildcraft Additions and Buildcraft 7.0.4/Buildcraft compat 7.0.2

**Comment by iTitus** [comment]
BC 7.0.4 is not yet compatible with BCA 2.1.3, try BC 7.0.3...

**Comment by AEnterprise** [comment]
update is comming
