### ISSUE TITLE
Refinary wont accept Buildcraft oil

### ISSUE THREAD

**Issue by Virezz** [BCA-Team/Buildcraft-Additions#417]
Hi,
I have a bit of a problem, im trying to feed a refinery with Oil ( BuildCraft|Energy:bucketOil ) and it wont be piped into the refinery at all
https://imgur.com/a/ZeMqG
Tried 2 alternatives here just to see if it was something with TE pipes but BC pipes doesnt do anything either.
Has power as NEI tooltip says
https://imgur.com/a/Nqy3G
Nothing in either of the tanks in the refinery GUI
https://imgur.com/a/yygKp

Mods is a variation of Resonant Rise (New mainline)
Mod info that i think is of relevancy

Forge 10.13.3.1401-1710ls
BUILDCRAFT-6.4.14.jar
BUILDCRAFTADDITIONS-1.7.10-2.1.2.jar
BUILDCRAFT-COMPAT-6.4.2.jar
LOGISTICSPIPES-0.8.3.118.jar
EUREKA-1.7.10-3.0.2.jar
Forestry 3.5.4.13

**Comment by Hirsu** [comment]
I'd like to add a +1 to this issue. 
I'm using the same set of mods as the OP.
The refinery multiblock structure builds just fine, but I can't get it to accept any oil.

**Comment by AEnterprise** [comment]
the problem is that i can't replicate this, though the latest BCA is for BC7 so it is possible that fixed it, not sure

**Comment by Virezz** [comment]
the latest BCA for BC7 crashes with BC6.x installed. and ofc alot of other mods including forestry and logistic pipes isnt up to speed for bc7 atleast not the version i have without going into dev builds of them.

basicly we are using the AT launchers resonate rise pack with new mainline checked under mod selection, i guess maybe download that and see if u can replicate that, might be a fluid dictionary change but its called BC energy when u creative NEI spawns in a bucket of oil that is used on the creative tanks

**Comment by AEnterprise** [comment]
i migrated to 7.0 with BCA cause not much work is being done on the 6.x branch, also BC 7 should be stable pretty soon

again: i know it doesn't work in the RR pack but i have no clue why, nothing should have been changed that would break it, i can only assume some other mod is doing something to the BC refinery recipes, it's that or a forge fluid change

**Comment by AEnterprise** [comment]
seems like this isn't an issue using BC7 and the most recent BCA, i have tried but failed to track down the cause, as a temp fix i sugest using minetweaker to manually add the recipes back in  (oil to fuel gass in 1:1 ratio, heat required is 120, gas to fuel in cooling tower is also 1:1 ratio with a heat production of 0.06)

**Comment by Virezz** [comment]
Hi again, 
What would your gas and oil be called so i can call it in a minetweaker recipe ?
I tried mt liquids and i cant see something obvious that is fuel gas there, i have oil and fuel.

Have 2 alternatives that im gonna try:

import mods.bcadditions.refinery;
mods.bcadditions.refinery.addRefineryRecipe(<liquid:oil> , <liquid:whatevergas is called>, <120>);

import mods.bcadditions.refinery;
mods.bcadditions.refinery.addRefineryRecipe(<BuildCraft|Energy:blockOil> , <liquid:whatevergas is called>, <120>);
now im not sure this is gonna work, im also not sure if the heat syntax is right and ofc missing the output liquid name according to http://bcadditions.ga/?page_id=605

**Comment by AEnterprise** [comment]
yeah that wiki page should be up to date, it seems like the fuel gas doesn't exist due to the fact that BCA makes that based on the refinery recipe, if another mod allows you to add fluids i sugest you do that, otherwise add a direct oil to fuel recipe
