### ISSUE TITLE
Heated Furnace Bug BCA 2.1.3

### ISSUE THREAD

**Issue by RatchetMP** [BCA-Team/Buildcraft-Additions#418]
So I was smelting dusts from Thermal Expansion and Tinkers and noticed if you leave a previously smelted ingot in the furnace the other dusts will smelt into that ingot. So turning Lead to Silver or Ardite to Cobalt but it doesn't work with vanilla ingots.

BCA Transmutation FTW

**Comment by AEnterprise** [comment]
hmm, probably the mod ingots are eighter metadata or nbt different and i'm probably not checking for that then
