### ISSUE TITLE
Cross Mod Interaction

### ISSUE THREAD

**Issue by acun1994** [BCA-Team/Buildcraft-Additions#422]
Version: 2.1.4
Mods affected: Botania (build 190)

Jumping on a Basic Duster and a Semi Automatic Duster does not register (no progress on item processing, WAILA reports agree) when a Soujourner's Sash is equipped.

**Comment by AEnterprise** [comment]
hmm, this is a botania bug, the sash is preventing the duster from knowing that someone landed on it

**Comment by AEnterprise** [comment]
so to be sure: it works without the sash but not with?

**Comment by acun1994** [comment]
Yup. If the sash is in player inventory (bauble inventory and normal inventory), the dusters don't register jumps. Once I place the sash in a chest, it works again

**Comment by AEnterprise** [comment]
alright, talked to the botania dev's and this is a thing we can't fix, the sash reduces your fall distance (2block buffer, compensates for the jump boost) but that makes MC think you didn't fall on the block at all, you'll have to un-equip your sash to the duster, sorry

**Comment by acun1994** [comment]
Yeah, read the issue over at Botania's Github. Shame though, but still just a minor bug.

**Comment by AEnterprise** [comment]
they might make a thing to fix it but atm there is nothing i can do about it
