### ISSUE TITLE
Coolin Tower Crash TileCoolingTower.onBlockActivated

### ISSUE THREAD

**Issue by KaneHart** [BCA-Team/Buildcraft-Additions#423]
Nothing changed but at times it seems to crash on it's own. We have had this on 2 diff servers and both times the cooling tower blocks were not touched as in moved, broken, placed, etc.

http://pastebin.com/ihmRR2BT

ADDED Issue:
At times not sure why but the fuel process seems to just fail randomly. As in it does not process anymore even if it's full of liquids. The only cure we have found is to rebuild the entire structure. 

Updated Issue on the process stop working:
Today's report is someone who was unable to produce fuel gas even though the entire setup worked fine for days. But all the sudden the gas was not producing but was at 120 temperature and full of oil and nothing down the line causing it to have to wait.

**Comment by AEnterprise** [comment]
note: probably a issue with data saving/loading, needs investigating
