### ISSUE TITLE
Can't create a new world BCA 2.1.4/BC 7.0.6

### ISSUE THREAD

**Issue by Xen1290** [BCA-Team/Buildcraft-Additions#425]
For the third time, if I remove dust registration(    B:shouldRegisterDusts=false  ), the game doesn't work, here the error:
https://gist.github.com/Xee1/342914842f857b7220ea
@AEnterprise 
In theory, is should was fixed long time ago, but that it still remain.
#397 
#361

**Comment by AEnterprise** [comment]
very odd, i can't figure out why this keeps returning

**Comment by AEnterprise** [comment]
calling @iTitus in on this one, i thought i fixed it but clearly missed something, a fresh pair of eyes on this would be the best way to handle this

**Comment by iTitus** [comment]
I will look into this.

**Comment by iTitus** [comment]
Can you please re-upload the crash report, I can't access it...

**Comment by AEnterprise** [comment]
easy to reproduce, turn off the config for dusts and make a new world

also any chanse of this being done in the next few days? would like to have this fixed in 2.2.0

**Comment by AEnterprise** [comment]
i just tried to recreate this but i failed, dissabled dust registration and made a new world, no crash, no dusts registered. could you provide a crashlog @Xen1290 ? also BCA and forge versions please

**Comment by iTitus** [comment]
This is the same thing I did seconds ago, nothing crashed...

**Comment by Xen1290** [comment]
Sure, but now I haven't the pc with me. please, wait until tonight(GMT+1) and I give you everything you need

**Comment by Xen1290** [comment]
Ok, so here all the information you need @AEnterprise , @iTitus 
Note: I tried to explain as well as possible, let me know if you do not understand something. I'm sorry if I made mistakes with English !

Here the error in console when I try to create a new world with B:shouldRegisterDusts=false, this appear in console, he doesn't create a crash report, because the game return me in the menu screen. This happen every time when I try to create a new world. Result: every time the game return me to menu screen, and if I go in singleplayer to find the world that I try to create, It doesn't appears, even restarting the game.
(P.S.For World Type I set Realistic Alpha from RWG)

https://gist.github.com/Xen1290/20b4e2b858f183d70934

Here the modlist that I'm using( 200+ mods):
https://gist.github.com/Xen1290/21d7eeee319dbf306bff (From NEIIntegration)
Forge 10.13.4.1448
BuildcraftAdditions-1.7.10-2.1.4
buildcraft-7.0.8
buildcraft-compat-7.0.7

Here the entire FML Log
https://gist.githubusercontent.com/Xen1290/48365b8503ca8378574a/raw/gistfile1.java

If i set B:shouldRegisterDusts=true, everything works fine.

**Comment by leSamo** [comment]
Could you try to reproduce it without AOBD?

**Comment by AEnterprise** [comment]
it is odd, can you reproduce with just BCA, BC and eureka and no other mods?

**Comment by leSamo** [comment]
So I tried it with
BC 7.0.9
BCA 2.2.0-205
Eureka IDK latest
and didn't crash.

**Comment by Xen1290** [comment]
Yes, I can confirm @leSamo . @AEnterprise But this is strange, maybe a mod is messing with your dust register?

**Comment by AEnterprise** [comment]
yeah, i sugest adding in the mods that have something to do with dusts till you find the offender

**Comment by Xen1290** [comment]
Yeah, I'll try it right now.

**Comment by Xen1290** [comment]
I FINALLY figured out the mod that have messed the dust register, I don't know why, but it is Flaxbeard's Steam Power - 1.7.10-0.28.7. Without it, everything works. @AEnterprise @iTitus 
I call @xbony2 if can help us to figure out that strange error.

**Comment by Xen1290** [comment]
EDIT: There are many mods that cause that crash, not only Flaxbeard... I'll try to find.

**Comment by AEnterprise** [comment]
alright so it is not on our side then thanks, hope you can find the mod/mods that cause it so it can be delt with

**Comment by Xen1290** [comment]
I hope I FINALLY figured out the problem, EVERY mod that add any type of dusts, doesn't work with B:shouldRegisterDusts=false . @AEnterprise 
I tried with AE2,IC2,EnderIO, every that mod doesn't work. I think is in your side. If you try to put BC,BCA,BCC, and IC2 or AE2 or any type of mod that add dusts and you set B:shouldRegisterDusts=false the error appear.

**Comment by AEnterprise** [comment]
that is very odd

**Comment by Xen1290** [comment]
Tested for example with : 
Eureka-1.7.10-3.0.2
buildcraft-7.0.9
BuildcraftAdditions-1.7.10-2.1.4
buildcraft-compat-7.0.8
EnderIO-1.7.10-2.3.0.388_beta

**Comment by Xen1290** [comment]
Yeah, very strange, I don't know what's going on with dust register.
Oh, I'm using MultiMC, I don't know if is useful.

**Comment by leSamo** [comment]
Maybe remove this config option before it gets fixed?

**Comment by AEnterprise** [comment]
removing the config option is not an option

**Comment by AEnterprise** [comment]
can you reproduce with the latest jenkinsbuild (http://ci.tterrag.com/job/Buildcraft-Additions/) if so can you give a new crashreport? the line number doesn't match with what i have in dev so don't know what is exactly crashing

**Comment by Xen1290** [comment]
Sure, tried with latest build on jenkins, same thing, here you are the error that appear in console:
https://gist.github.com/Xen1290/7a086ccd84ab8ea45796
@AEnterprise

**Comment by AEnterprise** [comment]
i think i found the error then, can you try again with build 209?

**Comment by Xen1290** [comment]
Same result with 209.... @AEnterprise  Here the error:
https://gist.github.com/Xen1290/f391d4fbd0b6828592b2

Oh, just another thing, this appear in console on startup, I don't know if is important, so:
[22:04:31] [Client thread/WARN] [FML]: ****************************************
[22:04:31] [Client thread/WARN] [FML]: * The object buildcraftAdditions.items.ItemRobotDebugTool@46d1ecea has been registered twice for the same name bcadditions:robotDebugTool.
[22:04:31] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:376)
[22:04:31] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:845)
[22:04:31] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:808)
[22:04:31] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:149)
[22:04:31] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:137)
[22:04:31] [Client thread/WARN] [FML]: * at buildcraftAdditions.compat.buildcraft.CompatBuildCraft.addRobotDebugTool(CompatBuildCraft.java:51)...
[22:04:31] [Client thread/WARN] [FML]: ****************************************

**Comment by AEnterprise** [comment]
pinging @iTitus

**Comment by AEnterprise** [comment]
jenkins is building yet another build, can you try that one?

**Comment by Xen1290** [comment]
Tried with 210... same thing @AEnterprise :

https://gist.github.com/Xen1290/eab2b524ad068afcd02b

**Comment by iTitus** [comment]
Nice solution ;)

**Comment by Xen1290** [comment]
Thank you! I'll try it

**Comment by AEnterprise** [comment]
it's what i should have done the first time :P
