### ISSUE TITLE
2.2.0 (Jenkins 206 (dev))

### ISSUE THREAD

**Issue by AgentK9** [BCA-Team/Buildcraft-Additions#428]
crash: https://gist.github.com/AgentK9/e26903c24f004cefe70e
Also: not sure if this is just because of being in a dev enviroment, but whatevs:
crash2: looks like incompat with new forge (.1445): https://gist.github.com/AgentK9/de2bdef613f9c8cb5b3e

**Comment by AEnterprise** [comment]
first crash is caused by buildcraft, second one should not be heapening, both are realy odd, can you try forge .1400 and a non dev environment?

**Comment by AEnterprise** [comment]
both crashes have same cause: mappings changed in the newer forge, compiled versions still work but the dev versions don't, downgrade forge or wait for a build compiled against newer forge
