### ISSUE TITLE
Assembly table recipes requiring ingots use considerably more in SMP

### ISSUE THREAD

**Issue by b0bst3r** [BCA-Team/Buildcraft-Additions#431]
Firstly this only occurs in SMP it doesn't seem to be an issue in SSP.

Buildcraft-7.0.9.jar with BuildcraftAdditions-1.7.10-2.1.4.jar and logisticspipes-0.9.1.15.jar and buildcraft-compat-7.0.8.jar

Removed LP - problem still there
Removed BC Compat - problem still there

An example - pipe wire (any color) should be 1 redstone, 1 rose red and 1 iron ingot  it shows in NEI as requiring 1 redstone, 1 rose red and 64 iron ingots.

Testing actual crafting of pipe wire and it does need and use 64 iron ingots.

So this is NEI showing the pipe wire with the above mods in SMP  - http://postimg.org/image/5194e5yvd/

Tried with BC 7.0.11 and same problem is there.

If I remove BCA the problem is no longer present.

**Comment by AEnterprise** [comment]
o.0

BCA 2.1.4 i have no idea at all how this could be heapening

calling @asiekierka for how the assembly table works and how i could be causing this as i'm only registering recipes

**Comment by AEnterprise** [comment]
unable to reproduce in my dev environment, can you try updating BC and BCC? that should fix the problem then

**Comment by b0bst3r** [comment]
I spent hours last night trying to narrow this down and although removing BCA resolves the issue it is also resolved by removing ThermalRecycling-1.7.10-0.3.8.4.jar.

I came to this conclusion by starting with BC and BCA (plus a few other core mods and working my way up until finding what caused the issue to manifest.

So not entirely sure what I've found lol

**Comment by b0bst3r** [comment]
And when I finally tracked down which mod caused this and go to bug report it I find it already done and fixed in an alpha release ...... https://github.com/OreCruncher/ThermalRecycling/issues/25

**Comment by AEnterprise** [comment]
alright, good to know that it has been fixed, very weird it doesn't heapen when BCA isn't installed though

**Comment by b0bst3r** [comment]
Yeah very weird seems more like a cross mod compatibility issue remove one or the other and the problem disappears.  So maybe it's something you are adding that breaks Thermal Recycling.  I dunno, I 'm only speculating as I can't write code for toffee.  I would suggest you chat with TR dev though and see if you can't see what and why.  Good luck :)

**Comment by asiekierka** [comment]
Thermal Recycling wasn't creating copies of the ItemStacks from recipes it was manipulating, from what I can see. This confused a reasonable chunk of the code.
