### ISSUE TITLE
Can't force old fuel production

### ISSUE THREAD

**Issue by jerry1333** [BCA-Team/Buildcraft-Additions#434]
Hi,
tried to force old oil to fuel recipe to be enabled but in any way it's not working.

Config:
B:MultiBlockRefining=false
B:forceEnableBCRefinery=true

and still bc refinery is converting oil to fuel gas.

**Comment by AEnterprise** [comment]
hmm, probably forgot to dissable the converter

**Comment by jerry1333** [comment]
Is this file responsible for this?
Buildcraft-Additions/src/main/java/buildcraftAdditions/utils/fluids/RefineryRecipeConverter.java

**Comment by MrKickkiller** [comment]
@jerry1333 : Probably, but deleting that file will not help. It will rather cause the build / jar / mod to fail.

**Comment by jerry1333** [comment]
@MrKickkiller Yes I know, don't have eclipse setup right now so I can't test it, but simple if should be enough to fix it.

**Comment by AEnterprise** [comment]
if you don't have eclipse, intellij or anything similar setup please DON'T try to fix it because you would not be able to test it at all

**Comment by AEnterprise** [comment]
*fixes, not fixex, stupid typo's

**Comment by jerry1333** [comment]
Thanks.
