### ISSUE TITLE
Can't add further upgrades to Kinetic Multi Tool

### ISSUE THREAD

**Issue by b0bst3r** [BCA-Team/Buildcraft-Additions#435]
Version 2.2.0 with BC 7.0.12

You can make the KMT no problem and add in a head but when it comes to upgrading the tool to add in another upgrade it doesn't seem to work.

The manual suggests you need a quartz chipset and gold stick however putting the KMT in the integration table only opens 1 slot and neither the gold stick or the quartz chipset are allowed in the table together.

NEI suggests this http://postimg.org/image/mnlkwowcp/ is the correct way to upgrade the tool (excuse the textures I was in the middle of Sphaxyfying it) but that doesn't work.

**Comment by AEnterprise** [comment]
NEI is correct in this case, the documentation needs an update
