### ISSUE TITLE
Texture issues (2.2.0)

### ISSUE THREAD

**Issue by InFerNos1** [BCA-Team/Buildcraft-Additions#436]
Machine Upgrade: 'Auto-Eject' has missing texture, as does 'Robot Debug Tool', but that might be intended as it's creative only.
Gasoline gas is a blue flame. It this is intended, it sure is weird.
![2015-06-24_22 06 20](https://cloud.githubusercontent.com/assets/1023518/8329516/48c268a0-1abd-11e5-83f5-2131dbff6457.png)

**Comment by AEnterprise** [comment]
robot debug tool is inteded, gasolene gas is odd, are you sure that is added by BCA?

**Comment by AEnterprise** [comment]
probably the same #438
