### ISSUE TITLE
Texture mismatch with fuel gas .

### ISSUE THREAD

**Issue by Deckee** [BCA-Team/Buildcraft-Additions#438]
This is not the fist time ive seen something like this. I though that this was fix in the 1.7.10 forge builds. But things break.
![2015-06-24_17 46 54](https://cloud.githubusercontent.com/assets/8199121/8343382/4002b012-1a9a-11e5-92a9-17590c6061da.png)
![2015-06-24_17 51 13](https://cloud.githubusercontent.com/assets/8199121/8343383/45d62bae-1a9a-11e5-9a00-cfbcbf0ad206.png)
![2015-06-24_17 51 41](https://cloud.githubusercontent.com/assets/8199121/8343385/474e518c-1a9a-11e5-9f1b-3fe368b976f9.png)
Edit: This was not a bug in BCA 2.1.4. only present in 2.2.0.

**Comment by AEnterprise** [comment]
o.0 very odd, i did not change a thing so must be a change on the forge side

**Comment by BigXplosion** [comment]
I know forge changed something that the texturemap is only build once now, not 2 times like before. This way a way to bring down the loading time. I haven't really looked into this and what it changed but it could have to do with it. But first we need to know what version of forge you are using.

**Comment by Deckee** [comment]
You were wondering what forge im using, the build is is 10.13.4.1470.

**Comment by Deckee** [comment]
The bc7 build im using is 7.0.9 with bc compat 7.0.4

**Comment by AEnterprise** [comment]
are there any other fluids affected? do you have optifine installed?

**Comment by Deckee** [comment]
Jus the fuel gas. my computer has more than enough power to run mc with optifine, optifine is not installed but fastcraft 1.21 is.

**Comment by BigXplosion** [comment]
@Deckee could you try and add this to your run arguments and see what happens ```-Dfml.skipFirstTextureLoad=false```

**Comment by AEnterprise** [comment]
thought of that but seems unlikely as i'm listening to the texture event so even if the first one doesn't work properly the second (complete) texture load should override it anyways and fix it

**Comment by Deckee** [comment]
I try the -Dfml.skipFirstTextureLoad=false argument and the fuel gas took the texture of rc steam fluid block.

**Comment by Deckee** [comment]
![2015-06-26_20 55 17](https://cloud.githubusercontent.com/assets/8199121/8389999/13adc5c6-1c46-11e5-8a1b-d17f9409c980.png)
And hers what the fluid block looks like.

**Comment by AEnterprise** [comment]
this get's weirder and weirder

**Comment by iTitus** [comment]
Does that happen without FastCraft?
Could you please try this with and without the special launch argument.
Also, does that happen with only BCA+BC?

**Comment by Deckee** [comment]
With out fast craft
![2015-06-27_17 01 45](https://cloud.githubusercontent.com/assets/8199121/8394083/a5091ba8-1cee-11e5-9dae-35ef4227c86f.png)

**Comment by Deckee** [comment]
"this get's weirder and weirder" AEnterprise
Im going to agree with that.

**Comment by jerry1333** [comment]
Same for me, using Resonant Rise pack + newest BCA (2.2.0).
![2015-06-29_21 22 55](https://cloud.githubusercontent.com/assets/984193/8416308/1dcf1936-1ea5-11e5-9741-77eb87703a0f.png)

**Comment by Xen1290** [comment]
I can confirm, other fluids are ok, only fuel gas.
Test on 200+ mods forge 10.13.4.1481 and BCA 2.2.0

**Comment by AEnterprise** [comment]
can you force a texture reload? (F3 + T) and let me know if that fixes it or not

**Comment by jerry1333** [comment]
Just tested clean install:
forge-1.7.10-10.13.4.1448-1.7.10-universal.jar
BUILDCRAFT-7.0.12.jar
BUILDCRAFTADDITIONS-1.7.10-2.1.4.jar
CODECHICKENCORE-1.7.10-1.0.7.46-UNIVERSAL.jar
EUREKA-1.7.10-3.0.2.jar
NOTENOUGHITEMS-1.7.10-1.0.5.111-UNIVERSAL.jar

Works well.
![2015-07-01_22 02 30](https://cloud.githubusercontent.com/assets/984193/8463721/042bc9a4-203d-11e5-8766-b4bd9d262f62.png)


When changed to BUILDCRAFTADDITIONS-1.7.10-2.2.0.jar texture is messed up again.
![2015-07-01_22 06 46](https://cloud.githubusercontent.com/assets/984193/8463769/7ee74f1a-203d-11e5-80d9-eed8215bf224.png)
F3+T don't change anything.

**Comment by Deckee** [comment]
f3+t doesn't fix the texture.

**Comment by AEnterprise** [comment]
hmm, so there must be some thing that i did change that is causing this, very weird
