### ISSUE TITLE
Error on Keyboard input

### ISSUE THREAD

**Issue by jre08** [BCA-Team/Buildcraft-Additions#440]
Pressing any key on the keyboard will crash Minecraft.  Here is the error report I receive:
I only receive this while using the 2.2.0 version.

---- Minecraft Crash Report ----
// There are four lights!

Time: 7/3/15 8:07 AM
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectByteBuffer.get(Unknown Source)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at buildcraftAdditions.listeners.KeyListener.InputEvent(KeyListener.java:30)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_173_KeyListener_InputEvent_KeyInputEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:540)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1873)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectByteBuffer.get(Unknown Source)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at buildcraftAdditions.listeners.KeyListener.InputEvent(KeyListener.java:30)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_173_KeyListener_InputEvent_KeyInputEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:540)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['john'/232, l='MpServer', x=286.79, y=65.62, z=60.85]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (129,64,125), Chunk: (at 1,4,13 in 8,7; contains blocks 128,0,112 to 143,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 187483 game time, 187483 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 55 total; [EntityPig['Pig'/133, l='MpServer', x=221.31, y=64.00, z=-3.53], EntityPig['Pig'/134, l='MpServer', x=222.06, y=64.00, z=6.16], EntityPig['Pig'/135, l='MpServer', x=216.53, y=64.00, z=17.97], EntityPig['Pig'/136, l='MpServer', x=222.50, y=66.00, z=25.50], EntityPig['Pig'/137, l='MpServer', x=215.81, y=65.00, z=22.06], EntityPig['Pig'/138, l='MpServer', x=217.06, y=65.00, z=34.06], EntityPig['Pig'/142, l='MpServer', x=224.81, y=63.00, z=-13.81], EntityPig['Pig'/143, l='MpServer', x=234.22, y=63.00, z=2.09], EntityPig['Pig'/144, l='MpServer', x=240.13, y=63.00, z=52.94], EntityBat['Bat'/148, l='MpServer', x=252.53, y=56.10, z=11.75], EntityBat['Bat'/149, l='MpServer', x=254.25, y=57.10, z=13.75], EntityBat['Bat'/150, l='MpServer', x=254.47, y=57.10, z=13.75], EntityPig['Pig'/151, l='MpServer', x=248.25, y=67.00, z=33.50], EntityPig['Pig'/152, l='MpServer', x=246.13, y=67.00, z=34.22], EntityPig['Pig'/153, l='MpServer', x=247.38, y=67.00, z=43.03], EntityBat['Bat'/154, l='MpServer', x=246.64, y=17.71, z=139.58], EntityBat['Bat'/156, l='MpServer', x=247.31, y=22.93, z=137.37], EntityBat['Bat'/159, l='MpServer', x=259.67, y=38.66, z=-5.71], EntityPig['Pig'/160, l='MpServer', x=256.50, y=63.00, z=24.31], EntityPig['Pig'/161, l='MpServer', x=265.03, y=65.00, z=48.97], EntitySquid['Squid'/162, l='MpServer', x=274.97, y=55.31, z=109.84], EntityPig['Pig'/173, l='MpServer', x=281.88, y=66.00, z=-15.78], EntityBat['Bat'/174, l='MpServer', x=281.74, y=38.00, z=19.48], EntityBat['Bat'/175, l='MpServer', x=278.51, y=39.10, z=21.51], EntityBat['Bat'/176, l='MpServer', x=280.41, y=19.10, z=37.75], EntityBat['Bat'/177, l='MpServer', x=285.55, y=18.26, z=55.69], EntityBat['Bat'/178, l='MpServer', x=279.25, y=40.10, z=55.56], EntitySquid['Squid'/179, l='MpServer', x=280.47, y=54.46, z=90.53], EntitySquid['Squid'/180, l='MpServer', x=284.92, y=51.31, z=88.68], EntitySquid['Squid'/181, l='MpServer', x=284.09, y=48.31, z=107.44], EntitySquid['Squid'/182, l='MpServer', x=286.44, y=58.25, z=105.59], EntitySquid['Squid'/183, l='MpServer', x=282.50, y=52.22, z=101.13], EntitySquid['Squid'/184, l='MpServer', x=284.50, y=50.38, z=100.41], EntitySquid['Squid'/185, l='MpServer', x=288.31, y=48.00, z=108.44], EntitySquid['Squid'/186, l='MpServer', x=281.94, y=51.38, z=109.78], EntitySquid['Squid'/187, l='MpServer', x=278.94, y=61.38, z=116.66], EntityPig['Pig'/198, l='MpServer', x=303.97, y=71.00, z=4.84], EntitySquid['Squid'/199, l='MpServer', x=303.51, y=56.19, z=75.59], EntitySquid['Squid'/200, l='MpServer', x=309.39, y=56.10, z=73.39], EntitySquid['Squid'/201, l='MpServer', x=300.50, y=53.00, z=92.41], EntitySquid['Squid'/202, l='MpServer', x=296.31, y=50.00, z=92.28], EntitySquid['Squid'/203, l='MpServer', x=291.54, y=52.87, z=90.81], EntitySquid['Squid'/204, l='MpServer', x=291.69, y=50.19, z=85.24], EntitySquid['Squid'/205, l='MpServer', x=295.13, y=53.84, z=107.97], EntitySquid['Squid'/206, l='MpServer', x=291.69, y=56.94, z=103.81], EntitySquid['Squid'/207, l='MpServer', x=295.56, y=50.66, z=122.69], EntityBat['Bat'/214, l='MpServer', x=311.53, y=53.10, z=-5.03], EntitySquid['Squid'/215, l='MpServer', x=308.47, y=56.00, z=70.47], EntityBat['Bat'/216, l='MpServer', x=306.20, y=35.00, z=82.62], EntityCow['Cow'/228, l='MpServer', x=335.47, y=68.00, z=-18.34], EntityBat['Bat'/229, l='MpServer', x=326.16, y=57.03, z=-6.67], EntityPig['Pig'/230, l='MpServer', x=320.31, y=69.00, z=10.13], EntityBlock['unknown'/358, l='MpServer', x=305.25, y=63.01, z=96.25], EntityPig['Pig'/233, l='MpServer', x=359.03, y=64.00, z=58.97], EntityClientPlayerMP['john'/232, l='MpServer', x=286.79, y=65.62, z=60.85]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 219522536 bytes (209 MB) / 514854912 bytes (491 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
	UCHIJAAAA	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.12} [BuildCraft] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.0.12} [BC Energy] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.0.12} [BC Factory] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.12} [BC Transport] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.0.12} [BC Builders] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.0.12} [BC Silicon] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	Additional-Buildcraft-Objects{MC1.7.10-BC7release3.0.1} [Additional Buildcraft Objects] (ABO-MC1.7.10-BC7-release3.0.1.jar) 
	UCHIJAAAA	additionalpipes{4.5.2} [Additional Pipes] (additionalpipes-4.5.2-hotfix1.jar) 
	UCHIJAAAA	Backpack{2.0.0} [Backpack] (backpack-2.0.0-1.7.x.jar) 
	UCHIJAAAA	betterrecords{1.7.10-1.1.2} [Better Records] (betterrecords-1.7.10-1.1.2.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.0.12} [BC Robotics] (buildcraft-7.0.12.jar) 
	UCHIJAAAA	Forestry{3.6.0.17} [Forestry for Minecraft] (forestry_1.7.10-3.6.0.17.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.0.8} [BuildCraft Compat] (buildcraft-compat-7.0.8.jar) 
	UCHIJAAAA	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCHIJAAAA	bcadditions{2.2.0} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.0.jar) 
	UCHIJAAAA	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (Minimap.jar) 
	UCHIJAAAA	examplemod{1.0} [Example Mod] (mod_XrayV2.01.jar) 
	UCHIJAAAA	Kradxns Xray{2.0} [Xray] (mod_XrayV2.01.jar) 
	UCHIJAAAA	NEIAddons{1.12.10.33} [NEI Addons] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar) 
	UCHIJAAAA	QuarryPlus{2.1.0} [QuarryPlus] (QuarryPlus-1.7.10-2.1.0.jar) 
	UCHIJAAAA	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	Roguelike{1.3.5} [Roguelike Dungeons] (roguelike-1.7.10-1.3.5(1).jar) 
	UCHIJAAAA	SolarFlux{1.7.10-0.8a} [Solar Flux] (SolarFlux-1.7.10-0.8a.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13394 Compatibility Profile Context 15.200.1023.7' Renderer: 'AMD Radeon HD 6570'
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6570 GL version 4.5.13394 Compatibility Profile Context 15.200.1023.7, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by iTitus** [comment]
Did you change your key bindings for "jump" and "forward" ?

**Comment by jre08** [comment]
I did for jump but not forward.   I have jump on my mouse.

**Comment by iTitus** [comment]
Ok, that is the cause of the issue.
For now you have to rebind the key to something on your keyboard, sorry.
We will see what we can so about that.

**Comment by AEnterprise** [comment]
yeah, will have to see if we can fix this

**Comment by iTitus** [comment]
I think TiCon had a similiar problem...

**Comment by jre08** [comment]
Thank you for all your hard ward.  I will be updating as soon as possible.

**Comment by AEnterprise** [comment]
there is no update out yet, not sure when i'll release it

**Comment by jre08** [comment]
Ok.. no problem  I didn't figure a release would be out just yet.
