### ISSUE TITLE
Config option for textures

### ISSUE THREAD

**Issue by AgentK9** [BCA-Team/Buildcraft-Additions#443]
I personally like the way the textures were before 2.2. I would like a config option to change between them

**Comment by AlexTheGre4t** [comment]
That can be sorted out. I'm gonna make a resource pack at least.

**Comment by AEnterprise** [comment]
best bet is a resourcepack by alex then, config option is a hassle

**Comment by AgentK9** [comment]
ok

**Comment by AgentK9** [comment]
no offence alex

**Comment by AlexTheGre4t** [comment]
None taken. I am also a huge fan of the old textures. But they were
designed from the original BC retexture ideas. They were then changed
within BC so I retextured BCA to match.

**Comment by AEnterprise** [comment]
whell with the new mod and seperating from BC i'm not sure what the eventual textures well be, original, these or others

**Comment by AEnterprise** [comment]
not gona do this in BCA itself

**Comment by AlexTheGre4t** [comment]
I'll get onto resource pack when I'm back from vacation

**Comment by AEnterprise** [comment]
when will you be back?

**Comment by AlexTheGre4t** [comment]
Sunday

**Comment by AEnterprise** [comment]
alright, you have time to do some textures next week then?

**Comment by AlexTheGre4t** [comment]
Yeah. Gonna have loads of time for the next 4 weeks

**Comment by AEnterprise** [comment]
great
