### ISSUE TITLE
Advanced Kinetic Buffer Plating block breaking on placement?

### ISSUE THREAD

**Issue by Zetharion** [BCA-Team/Buildcraft-Additions#444]
Tried to start building the Advanced Kinetic Buffer and when placing down a plating block, it broke into 2 Diamond Kinesis Pipes, 4 gold Ingots, and 3 Iron Ingots.  We do have Eureka 3.0.2, BCA 2.2.0 and BC 7.0.12, BC Compat 7.0.8.  Its a custom pack on Curse called Qmunity Subscriber Modpack.  

If it matters, I made 2 Large Kinetic Buffers and placed them down but they had red x's on all the sides and the book does not show that the Advanced Buffer has been unlocked.

**Comment by AgentK9** [comment]
Then you need to unlock it in the book

**Comment by Zetharion** [comment]
Yeah, I just crashed the server trying to make the 2x2x2 large energy buffer.

**Comment by AEnterprise** [comment]
the drops are indeed incorrect, the recipe changed and i completely forgot to fix the drops

as for the crash: i'll need a crashlog, without it it's impossible to know what went wrong that needs fixing

**Comment by Zetharion** [comment]
Ok, got a copy of the crash report from the server admin:

http://pastebin.com/zbL1gDhd

**Comment by AEnterprise** [comment]
alright, eureka crash, will take a look and fix

**Comment by AEnterprise** [comment]
fixed
