### ISSUE TITLE
KEB minecarts

### ISSUE THREAD

**Issue by AgentK9** [BCA-Team/Buildcraft-Additions#445]
I know there are many more efficient ways to transport energy, but for completeness' sake, WHY NOT???

**Comment by iTitus** [comment]
I actually do like the idea :D

**Comment by AEnterprise** [comment]
why not? cause i didn't get arround to doing it, also with the new mod migration might take a bit

**Comment by BigXplosion** [comment]
Well we talked about this once in IRC, I liked the idea but I guess no new features for BCA anymore? only for KR?

**Comment by AEnterprise** [comment]
as we're gona be moving BCA stuff to KR i sugest adding new features directly to there, saves the hassle of having to port it later

**Comment by BigXplosion** [comment]
yeah what I thought :D

**Comment by AgentK9** [comment]
I realize that, @AEnterprise. just putting it out there

**Comment by AEnterprise** [comment]
closing, will be something for the new mod
