### ISSUE TITLE
Tool Core incompatible to integration table of buildcraft-1.7.10-7.0.9

### ISSUE THREAD

**Issue by krakel** [BCA-Team/Buildcraft-Additions#446]
The integration table was changed on buildcraft-1.7.10-7.0.9. The parts gold gear and diamond chipset can not put together in this new table to create the Tool Core.

**Comment by iTitus** [comment]
The recipe should exist. I will check now.

**Comment by iTitus** [comment]
![2015-08-19_23 08 15](https://cloud.githubusercontent.com/assets/5154317/9369073/46df3668-46c7-11e5-9d25-148509f2e21d.png)

**Comment by DerOli82** [comment]
I've updated all BuildCraft related mods and now it works.

**Comment by AEnterprise** [comment]
just a side note: integration recipes with the tool itself are a bit buggy, hope to fix that later this week
