### ISSUE TITLE
[Website Offline] Config options

### ISSUE THREAD

**Issue by spannerman79** [BCA-Team/Buildcraft-Additions#448]
Hi there,
What options in your config do i need to change to disable the villager and the powerplant from creating/spawning?

**Comment by AEnterprise** [comment]
there are no config options to dissable those, there is a new config option to dissable the power pipes in the structure cause that's the part that si crashing

**Comment by spannerman79** [comment]
> there are no config options to dissable those

That is such a pity.  Would you consider adding those config options to a "to-do" list for your mod?

**Comment by AEnterprise** [comment]
why would you want to dissable the whole thing?

**Comment by spannerman79** [comment]
While I love your mod and how it extends BuildCraft with the other mods I have running on a private server that myself and a couple of friends share I find the less needed to be run code wise should - in theory - would be better.

Hence why I asked if there was an option/config switch to disable villager and structure spawning for your mod specifically.

If you have no intention to fair enough and simply close this issue - it is your mod after all which I am using freely.

**Comment by AEnterprise** [comment]
to be honest i forgot about this issue for a bit, i'm making a new mod and all BCA content will move to it (it will be for minecraft 1.8.8 anyways) so i'm not gona realy bother with this as i see no real reson to, if you want to dissable unneeded code to run you can just dissable village generation all together
