### ISSUE TITLE
NoClassDefFoundError server

### ISSUE THREAD

**Issue by SvEgiiVEteR** [BCA-Team/Buildcraft-Additions#449]
BuildcraftAdditions-1.7.10-2.2.1.jar
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/model/ModelBiped
http://paste.ubuntu.com/12225398/

**Comment by iTitus** [comment]
Looks like a missing @SideOnly annotation

**Comment by AEnterprise** [comment]
darn it
