### ISSUE TITLE
The NEW bc-additions crashing when clicking the energy buffer

### ISSUE THREAD

**Issue by Sasikaa** [BCA-Team/Buildcraft-Additions#450]
The crash report:
http://pastebin.com/xKzQeDK5

(The energy buffer connected mekanism elite energy cable. The energy cable connected, AE2 machines, Mekanism machine, Thermal Exp. machine. The energy input the Energy buffer is tesseract-->elite cable--->buffer, and mekanism wind turbine (3)--->elite cable--->buffer)

**Comment by AEnterprise** [comment]
is it actually storing power?

**Comment by AEnterprise** [comment]
closing due to lack of input and unable to reproduce, i'll reopen if someone can give me more info on how to reproduce
