### ISSUE TITLE
Update to Buildcraft 7.1

### ISSUE THREAD

**Issue by erkro1** [BCA-Team/Buildcraft-Additions#451]
Since Buildcraft 7.1 just got a stable release, will you update BC-Additions to work with it? (Or are there minor changes and will it still work?)

**Comment by AEnterprise** [comment]
in theory it should work, just test and and let me know if it blows up

**Comment by erkro1** [comment]
I haven't tested it very good (only seeing if it started up and if an old world could be loaded), but that seemed to work. Thanks!

**Comment by Be-Cool-Man** [comment]
I have not found misconduct...

**Comment by iTitus** [comment]
That's good to hear ;)
