### ISSUE TITLE
crash with large kinetic energy buffer

### ISSUE THREAD

**Issue by romanticjo** [BCA-Team/Buildcraft-Additions#456]
Playing revolution pack on AtLauncher, got this:

https://gist.github.com/romanticjo/9ebc493bb66fcd9ab165

**Comment by AEnterprise** [comment]
should be easy enough to fix

**Comment by romanticjo** [comment]
Sweet!
Where are the downloads for the mod? I'll send a link to the pack maintainer.

**Comment by AEnterprise** [comment]
there is no new version out yet, should be one up tomorow though
