### ISSUE TITLE
BCA shipping outdated RF api

### ISSUE THREAD

**Issue by SvEgiiVEteR** [BCA-Team/Buildcraft-Additions#461]
http://hastebin.com/egizowahen.md
Look at line 288 of the hastebin paste.

**Comment by AEnterprise** [comment]
didn't know that BCA had an older version of the RF api, just remove the folder from the BCA jar and it should work, that's not the cause of the crash btw

**Comment by SvEgiiVEteR** [comment]
yes I know that is not)
just I saw it in the log and decided to write.
what kind of a folder to remove from mod?

**Comment by AEnterprise** [comment]
the cofh one, unless they made fundamental changes to the rf api it should just work fine

**Comment by janagyjr** [comment]
I'm having the same issue with BCA and EnderIO
https://github.com/SleepyTrousers/EnderIO/issues/4017

**Comment by AEnterprise** [comment]
sadly BCA is no longer maintained. due to a lack of time from me and the quitting of texture artists there will sadly no longer be any updates to it.

you can open the BCA jar with 7zip/winrar and remove the cofh folder from it, that will remove the shipped api

**Comment by janagyjr** [comment]
Upgrading my Forge version to 1614 for 1.7.10 fixed the issue.

**Comment by janagyjr** [comment]
Is there a possibility of someone else picking it up from you for maintenance?

**Comment by AEnterprise** [comment]
i wouldn't object to someone picking up the torch and continuing the mod as long as the style and philosophy are continued
