### ISSUE TITLE
Modpack Perms

### ISSUE THREAD

**Issue by AgentK9** [BCA-Team/Buildcraft-Additions#464]
Can I have perms for my modpack? Atlauncher, if that makes a difference

**Comment by AgentK9** [comment]
Also needed for eureka

**Comment by AEnterprise** [comment]
no explicit permission needed: as stated on different places multiple times now: all my mods can be used freely in any modpacks. just make sure i get bug reports from it if there are issues (when using the latest version ofc)

**Comment by AgentK9** [comment]
Thanks!
