### ISSUE TITLE
Ender IO compatibility

### ISSUE THREAD

**Issue by MIGA2001** [BCA-Team/Buildcraft-Additions#467]
I used the addon with EnderIO and got this issue
EnderIO: Found the following problem(s) with your installation:
                  * An unsupportted old RF API is installed (1.7.10R1.0.1 from BuildcraftAdditions-1.7.10-2.2.5.jar).
                    Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

**Comment by AEnterprise** [comment]
i would need the full crashlog (in a gist or pastebin preferably) to know for sure but i doubt the RF api version is the cause of any crash, that's only a very minor version change

**Comment by MIGA2001** [comment]
[crash-2017-04-13_21.43.36-client.txt](https://github.com/BCA-Team/Buildcraft-Additions/files/920634/crash-2017-04-13_21.43.36-client.txt)

**Comment by iTitus** [comment]
That looks like a potion ID conflict. Try to remove mods that potion or status effects one by one and it you find the culprits (there are always two sides to an id conflict) try to change the IDs in their respective configs. If that doesn't work try to ask for help on their respective issue trackers.

**Comment by iTitus** [comment]
The API thing listed at the bottom is not the cause of the crash. Also BCA doesn't add potion effects.

**Comment by AEnterprise** [comment]
yep potion conflicts do not have anything to do with, BCA, EIO or the RF api
