### ISSUE TITLE
Not working without Eureka mod

### ISSUE THREAD

**Issue by MPeti1** [BCA-Team/Buildcraft-Additions#469]
Forge said me any version of Eureka is required, and in the log i found it's only required by this mod. Could you fix it?

**Comment by AEnterprise** [comment]
this is not a bug, Eureka is a mod i made specificaly for BCA and is a required mod that hold the tech progression.

**Comment by MPeti1** [comment]
Oh, then sorry. If i put in eureka, can i set it to only use the progression system for BCA?

**Comment by AEnterprise** [comment]
only BCA uses it, it won't affect any other mods

**Comment by MPeti1** [comment]
Ok, thanks :D

**Comment by MPeti1** [comment]
Had a look on the mod's code, and it seems I've found a solution. In the mod's config file I found you have a setting `B:"Enable Mars Space Station"`, I've set it to false and it works now. Could you check in the beginning of `post init` if the id of the planets are already used by other mods? You could just send a message with the crash (throw an exception with a custom cause) or you could make a screen like when Forge finds mod version conflicts (like [this](https://i.ytimg.com/vi/2NaLzySvmH8/hqdefault.jpg)) if one of the id's are already used
