### ISSUE TITLE
Semi automatic Duster puts items back into the input hopper

### ISSUE THREAD

**Issue by ProxyPlayerHD** [BCA-Team/Buildcraft-Additions#470]
Doesn't matter what side the hopper is on or if there is a chest next to the machine... for some reason the Semi-Autoamtic Duster ALWAYS puts the dust into the hopper. and if there is no space in the hopper the dust gets deleted

even when i use pipes it rather deletes the dust than to just put it into the damn chest... why?

it basically makes it impossible to actually use the block unless you only have an output chest but no input

also how about an option to disable the pointless self destruct feature of KEBs? it has no point in existing and is just a potential hazard so not having an option to turn it off just seems weird.

**Comment by AEnterprise** [comment]
sneak click on the block with the machine configurator in hand to configure the in and output sides

as for pipes, it should work with BC pipes, not sure what pipes you are using

the self destruct is not that dangerous, you need to click it twice and has a delay. there might be a config option to disable in the config? not sure i ever made one or not

**Comment by ProxyPlayerHD** [comment]
there is no option in the config to disable it.

also i used Ender IO Conduits. even when they were set to input and output it was deleting items. why can't it just throw the items into the world instead of deleting them?

anyways i'll try the configurator, thanks for the help

**Comment by AEnterprise** [comment]
it should do that, but it means the enderio conduits are probably accepting them, if they vanish there probably is a bug somewhere but no clue if it's on the BCA or enderio side

**Comment by ProxyPlayerHD** [comment]
I mean the disappearing items must be in BCA sides since it happens with basically any inventory that is full

**Comment by iTitus** [comment]
Have you checked if the items are lying on the floor?

**Comment by iTitus** [comment]
Relevant code snippets:
Duster: https://github.com/BCA-Team/Buildcraft-Additions/blob/2.2.x/src/main/java/buildcraftAdditions/tileEntities/Bases/TileDusterWithConfigurableOutput.java#L103-L106

Utils.outputStack(...): https://github.com/BCA-Team/Buildcraft-Additions/blob/2.2.x/src/main/java/buildcraftAdditions/utils/Utils.java#L225-L289

Utils.dropItemstack(...): https://github.com/BCA-Team/Buildcraft-Additions/blob/2.2.x/src/main/java/buildcraftAdditions/utils/Utils.java#L172-L184

**Comment by AEnterprise** [comment]
side note on that: due to the way how minecraft works, it can happen things get stuck in a wall or even teleport through them if a duster is right next to one
